packages:
  - client
  - server
  - site
  - shared
  - video
injectWorkspacePackages: true
allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  electron: false
  electron-winstaller: false
  esbuild: true
  prisma: true
