/**
 * 由 scripts/animation/generate_animation_catalog_entries.cjs 从 UE 资产策选清单生成。
 * 请先更新 animationCatalogSelection.json，再重新生成此文件。
 */

export interface AnimationCatalogPackEntry {
  readonly id: string;
  readonly groupId: string;
  readonly sourcePack: string;
  readonly label: string;
}

export interface AnimationCatalogEntry {
  readonly id: string;
  readonly clipName: string;
  readonly name: string;
  readonly actionType: string;
  readonly classificationId: string;
  readonly classificationLabel: string;
  readonly actorKind: string;
  readonly actorKindLabel: string;
  readonly posture: string;
  readonly postureLabel: string;
  readonly weaponType: string;
  readonly weaponTypeLabel: string;
  readonly dedupeKey: string;
  readonly isIdleVariant: boolean;
  readonly groupId: string;
  readonly groupLabel: string;
  readonly packId: string;
  readonly packLabel: string;
  readonly sourcePack: string;
  readonly sourceAssetPath: string;
  readonly sourceAssetName: string;
  readonly sourceSkeleton: string;
  readonly inPlace: boolean;
  readonly inPlaceEvidence: "source-path" | "asset-name" | "unmarked-non-root";
  readonly durationSeconds: number;
  readonly sourceDurationSeconds: number;
  readonly catalogDurationSeconds: number;
}

export const ANIMATION_CATALOG_PACKS = [
  {
    "id": "unreal-daily-male-locomotion",
    "groupId": "unreal-daily",
    "sourcePack": "MaleLocomotionSet",
    "label": "男性移动套装"
  },
  {
    "id": "unreal-daily-sitting",
    "groupId": "unreal-daily",
    "sourcePack": "SittingAnimations",
    "label": "坐姿生活套装"
  },
  {
    "id": "unreal-daily-parkour",
    "groupId": "unreal-daily",
    "sourcePack": "ParkourAnimations",
    "label": "跑酷翻越套装"
  },
  {
    "id": "unreal-daily-mc-idles",
    "groupId": "unreal-daily",
    "sourcePack": "MC_Idles_Pack",
    "label": "多样待机套装"
  },
  {
    "id": "unreal-daily-roll-dodge",
    "groupId": "unreal-daily",
    "sourcePack": "RollDodgeDashSet",
    "label": "翻滚闪避套装"
  },
  {
    "id": "unreal-daily-dialogue",
    "groupId": "unreal-daily",
    "sourcePack": "Dialogue_mocap",
    "label": "对话表演套装"
  },
  {
    "id": "unreal-daily-sleep",
    "groupId": "unreal-daily",
    "sourcePack": "SleepAnimPack",
    "label": "睡眠套装"
  },
  {
    "id": "unreal-daily-female-interact",
    "groupId": "unreal-daily",
    "sourcePack": "FemInteractAnimSet",
    "label": "女性互动套装"
  },
  {
    "id": "unreal-interaction-vendors",
    "groupId": "unreal-interaction",
    "sourcePack": "Vendors_And_Customers",
    "label": "商贩与顾客套装"
  },
  {
    "id": "unreal-interaction-item-pickup",
    "groupId": "unreal-interaction",
    "sourcePack": "ItemPickupSet",
    "label": "拾取物品套装"
  },
  {
    "id": "unreal-interaction-npcs",
    "groupId": "unreal-interaction",
    "sourcePack": "NPCsBundle",
    "label": "NPC 生活动作套装"
  },
  {
    "id": "unreal-interaction-activations",
    "groupId": "unreal-interaction",
    "sourcePack": "Activations_mocap",
    "label": "门阀与机关互动套装"
  },
  {
    "id": "unreal-interaction-survival",
    "groupId": "unreal-interaction",
    "sourcePack": "Survival_Anims",
    "label": "生存制作套装"
  },
  {
    "id": "unreal-interaction-drinking",
    "groupId": "unreal-interaction",
    "sourcePack": "DrinkingAnimations",
    "label": "饮酒互动套装"
  },
  {
    "id": "unreal-interaction-car",
    "groupId": "unreal-interaction",
    "sourcePack": "CarInteractAnimations_VOL1",
    "label": "车辆互动套装"
  },
  {
    "id": "unreal-interaction-phoenyx",
    "groupId": "unreal-interaction",
    "sourcePack": "PhoenyxAnimPack3",
    "label": "桌面与游泳互动套装"
  },
  {
    "id": "unreal-misc-clazy",
    "groupId": "unreal-misc",
    "sourcePack": "CLazyAnimpack",
    "label": "通用移动套装"
  },
  {
    "id": "unreal-misc-kawaii",
    "groupId": "unreal-misc",
    "sourcePack": "KawaiiAnimations",
    "label": "可爱战斗套装"
  },
  {
    "id": "unreal-misc-scared",
    "groupId": "unreal-misc",
    "sourcePack": "Scared_01",
    "label": "惊恐反应套装"
  },
  {
    "id": "unreal-misc-morbid",
    "groupId": "unreal-misc",
    "sourcePack": "MorbidMotions_Pack",
    "label": "惊悚变异套装"
  },
  {
    "id": "unreal-misc-taunts",
    "groupId": "unreal-misc",
    "sourcePack": "TauntsPack",
    "label": "挑衅手势套装"
  },
  {
    "id": "unreal-misc-couples",
    "groupId": "unreal-misc",
    "sourcePack": "Couples_Anim_Pack",
    "label": "配对互动套装"
  },
  {
    "id": "unreal-misc-crowd",
    "groupId": "unreal-misc",
    "sourcePack": "CrowdAnimations",
    "label": "群演手势套装"
  },
  {
    "id": "unreal-misc-pedestrian-walks",
    "groupId": "unreal-misc",
    "sourcePack": "Pedestrian_Walks_01",
    "label": "行人步态套装"
  },
  {
    "id": "unreal-misc-morro",
    "groupId": "unreal-misc",
    "sourcePack": "MorroMotion",
    "label": "舞蹈表演套装"
  },
  {
    "id": "unreal-misc-climbing",
    "groupId": "unreal-misc",
    "sourcePack": "ClimbingAnimationSet",
    "label": "攀爬墙面套装"
  },
  {
    "id": "unreal-misc-irap",
    "groupId": "unreal-misc",
    "sourcePack": "IRAP",
    "label": "受伤与恢复套装"
  },
  {
    "id": "unreal-misc-preacher",
    "groupId": "unreal-misc",
    "sourcePack": "PreacherAnimations",
    "label": "祈祷演讲套装"
  },
  {
    "id": "unreal-misc-supporter",
    "groupId": "unreal-misc",
    "sourcePack": "suppoter_motion",
    "label": "助威动作套装"
  },
  {
    "id": "unreal-misc-female-mocap",
    "groupId": "unreal-misc",
    "sourcePack": "Female_Mocap_AnimPackVol1",
    "label": "女性生活表演套装"
  },
  {
    "id": "unreal-hand-combat-fight",
    "groupId": "unreal-hand-combat",
    "sourcePack": "FightAnimations",
    "label": "基础格斗套装"
  },
  {
    "id": "unreal-hand-combat-fighter",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Fighter_Animations",
    "label": "战士格斗套装"
  },
  {
    "id": "unreal-hand-combat-boxer",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Unleashed_Boxer",
    "label": "拳击套装"
  },
  {
    "id": "unreal-hand-combat-muaythai",
    "groupId": "unreal-hand-combat",
    "sourcePack": "MuayThai_AnimSet",
    "label": "泰拳套装"
  },
  {
    "id": "unreal-hand-combat-wingchun",
    "groupId": "unreal-hand-combat",
    "sourcePack": "wingchun_Animset",
    "label": "咏春套装"
  },
  {
    "id": "unreal-hand-combat-ninja",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Ninja_AnimSet",
    "label": "忍者徒手套装"
  },
  {
    "id": "unreal-hand-combat-special-moves",
    "groupId": "unreal-hand-combat",
    "sourcePack": "SpecialMoves_Energy",
    "label": "能量特技套装"
  },
  {
    "id": "unreal-hand-combat-finisher",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Finisher_Animations",
    "label": "终结技套装"
  },
  {
    "id": "unreal-hand-combat-lucy",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Lucy",
    "label": "女性格斗套装"
  },
  {
    "id": "unreal-hand-combat-demon",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Demon_Anims",
    "label": "恶魔动作套装"
  },
  {
    "id": "unreal-hand-combat-zombie",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Zombie_Anims",
    "label": "僵尸动作套装"
  },
  {
    "id": "unreal-hand-combat-ghost",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Ghost_Creature_Anims",
    "label": "幽灵动作套装"
  },
  {
    "id": "unreal-hand-combat-flying-mage",
    "groupId": "unreal-hand-combat",
    "sourcePack": "FlyingMageAnimSet",
    "label": "飞行法师套装"
  },
  {
    "id": "unreal-hand-combat-magical",
    "groupId": "unreal-hand-combat",
    "sourcePack": "MagicalAnimSet",
    "label": "魔法施法套装"
  },
  {
    "id": "unreal-hand-combat-classic-female-ghost",
    "groupId": "unreal-hand-combat",
    "sourcePack": "ClassicFemaleGhost",
    "label": "经典女鬼套装"
  },
  {
    "id": "unreal-hand-combat-monsters",
    "groupId": "unreal-hand-combat",
    "sourcePack": "41_Animations_Monsters",
    "label": "怪物动作套装"
  },
  {
    "id": "unreal-hand-combat-creature-sit",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Animations_Creature",
    "label": "生物地面动作套装"
  },
  {
    "id": "unreal-hand-combat-creatures",
    "groupId": "unreal-hand-combat",
    "sourcePack": "Creatures_animations",
    "label": "生物攻击套装"
  },
  {
    "id": "unreal-weapon-combat-sword",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "Sword_Animations",
    "label": "标准剑术套装"
  },
  {
    "id": "unreal-weapon-combat-katana",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "Katana_Animations",
    "label": "武士刀套装"
  },
  {
    "id": "unreal-weapon-combat-sword-pro",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "SwordAnimsetPro",
    "label": "剑术进阶套装"
  },
  {
    "id": "unreal-weapon-combat-wudang",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "WudangSword_Animset",
    "label": "武当剑套装"
  },
  {
    "id": "unreal-weapon-combat-rapier",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "Rapier_AnimSet",
    "label": "刺剑套装"
  },
  {
    "id": "unreal-weapon-combat-spear",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "SpearAndHalberdAnimset",
    "label": "长枪与戟套装"
  },
  {
    "id": "unreal-weapon-combat-dual-blade",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "Orientalism_Dual_Blade_Anim_Set",
    "label": "双刃套装"
  },
  {
    "id": "unreal-weapon-combat-pistol",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "PistolAnimsetPro",
    "label": "手枪套装"
  },
  {
    "id": "unreal-weapon-combat-mage",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "Mage",
    "label": "法师武器套装"
  },
  {
    "id": "unreal-weapon-combat-heavy-hammer",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "HeavyHammer",
    "label": "重锤套装"
  },
  {
    "id": "unreal-weapon-combat-grim-reaper",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "GrimReaperSet",
    "label": "死神镰刀套装"
  },
  {
    "id": "unreal-weapon-combat-sword-sheath",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "Sword_sheath_AnimSet",
    "label": "拔刀收刀套装"
  },
  {
    "id": "unreal-weapon-combat-stealth-knife",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "StealthFinishers_KnifeAndHand",
    "label": "潜行匕首套装"
  },
  {
    "id": "unreal-weapon-combat-ghost-samurai",
    "groupId": "unreal-weapon-combat",
    "sourcePack": "GhostSamurai_Bundle",
    "label": "幽灵武士套装"
  }
] as const;

export const ANIMATION_CATALOG_ENTRIES = [
  {
    "id": "unreal-daily-male-locomotion-walk-backward",
    "clipName": "C57_unreal_daily_male_locomotion_walk_backward",
    "name": "后退行走",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "walk-backward",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-male-locomotion",
    "packLabel": "男性移动套装",
    "sourcePack": "MaleLocomotionSet",
    "sourceAssetPath": "/Game/_AnimDaily/MaleLocomotionSet/Animations/Mannequin_UE4/InPlace/Walk/A_INP_WalkBwd_Loop",
    "sourceAssetName": "A_INP_WalkBwd_Loop",
    "sourceSkeleton": "/Game/_AnimDaily/MaleLocomotionSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 0.9667,
    "sourceDurationSeconds": 0.9667,
    "catalogDurationSeconds": 0.9667
  },
  {
    "id": "unreal-daily-male-locomotion-jog-forward",
    "clipName": "C57_unreal_daily_male_locomotion_jog_forward",
    "name": "向前慢跑",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jog-forward",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-male-locomotion",
    "packLabel": "男性移动套装",
    "sourcePack": "MaleLocomotionSet",
    "sourceAssetPath": "/Game/_AnimDaily/MaleLocomotionSet/Animations/Mannequin_UE4/InPlace/Jog/A_INP_JogFwd_Loop",
    "sourceAssetName": "A_INP_JogFwd_Loop",
    "sourceSkeleton": "/Game/_AnimDaily/MaleLocomotionSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 0.7,
    "sourceDurationSeconds": 0.7,
    "catalogDurationSeconds": 0.7
  },
  {
    "id": "unreal-daily-male-locomotion-run-forward",
    "clipName": "C57_unreal_daily_male_locomotion_run_forward",
    "name": "向前奔跑",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "run-forward",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-male-locomotion",
    "packLabel": "男性移动套装",
    "sourcePack": "MaleLocomotionSet",
    "sourceAssetPath": "/Game/_AnimDaily/MaleLocomotionSet/Animations/Mannequin_UE4/InPlace/Run/A_INP_RunFwd_Loop",
    "sourceAssetName": "A_INP_RunFwd_Loop",
    "sourceSkeleton": "/Game/_AnimDaily/MaleLocomotionSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 0.5667,
    "sourceDurationSeconds": 0.5667,
    "catalogDurationSeconds": 0.5667
  },
  {
    "id": "unreal-daily-male-locomotion-crouch-forward",
    "clipName": "C57_unreal_daily_male_locomotion_crouch_forward",
    "name": "蹲伏前进",
    "actionType": "move",
    "classificationId": "crouching",
    "classificationLabel": "蹲伏",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "crouching",
    "postureLabel": "蹲伏",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "crouch-forward",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-male-locomotion",
    "packLabel": "男性移动套装",
    "sourcePack": "MaleLocomotionSet",
    "sourceAssetPath": "/Game/_AnimDaily/MaleLocomotionSet/Animations/Mannequin_UE4/InPlace/Crouch/A_INP_CrouchFwd_Loop",
    "sourceAssetName": "A_INP_CrouchFwd_Loop",
    "sourceSkeleton": "/Game/_AnimDaily/MaleLocomotionSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1.2,
    "sourceDurationSeconds": 1.2,
    "catalogDurationSeconds": 1.2
  },
  {
    "id": "unreal-daily-male-locomotion-jump-forward",
    "clipName": "C57_unreal_daily_male_locomotion_jump_forward",
    "name": "向前跳跃落地",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jump-forward",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-male-locomotion",
    "packLabel": "男性移动套装",
    "sourcePack": "MaleLocomotionSet",
    "sourceAssetPath": "/Game/_AnimDaily/MaleLocomotionSet/Animations/Mannequin_UE4/InPlace/Jump/A_INP_JumpFwd_Land",
    "sourceAssetName": "A_INP_JumpFwd_Land",
    "sourceSkeleton": "/Game/_AnimDaily/MaleLocomotionSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 0.2,
    "sourceDurationSeconds": 0.2,
    "catalogDurationSeconds": 0.2
  },
  {
    "id": "unreal-daily-male-locomotion-falling",
    "clipName": "C57_unreal_daily_male_locomotion_falling",
    "name": "空中下落",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "falling",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-male-locomotion",
    "packLabel": "男性移动套装",
    "sourcePack": "MaleLocomotionSet",
    "sourceAssetPath": "/Game/_AnimDaily/MaleLocomotionSet/Animations/Mannequin_UE4/InPlace/Jump/A_INP_Falling_Loop",
    "sourceAssetName": "A_INP_Falling_Loop",
    "sourceSkeleton": "/Game/_AnimDaily/MaleLocomotionSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 0.9,
    "sourceDurationSeconds": 0.9,
    "catalogDurationSeconds": 0.9
  },
  {
    "id": "unreal-daily-parkour-walk-in-place",
    "clipName": "C57_unreal_daily_parkour_walk_in_place",
    "name": "向前行走",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "walk-in-place",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-parkour",
    "packLabel": "跑酷翻越套装",
    "sourcePack": "ParkourAnimations",
    "sourceAssetPath": "/Game/_AnimDaily/ParkourAnimations/Animations/UE4_Skelet/Base/InPlace_Locomotion/A_Walk_IP",
    "sourceAssetName": "A_Walk_IP",
    "sourceSkeleton": "/Game/_AnimDaily/ParkourAnimations/Characters/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 0.9333,
    "sourceDurationSeconds": 0.9333,
    "catalogDurationSeconds": 0.9333
  },
  {
    "id": "unreal-daily-parkour-run-in-place",
    "clipName": "C57_unreal_daily_parkour_run_in_place",
    "name": "向前奔跑",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "run-in-place",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-parkour",
    "packLabel": "跑酷翻越套装",
    "sourcePack": "ParkourAnimations",
    "sourceAssetPath": "/Game/_AnimDaily/ParkourAnimations/Animations/UE4_Skelet/Base/InPlace_Locomotion/A_Run_IP",
    "sourceAssetName": "A_Run_IP",
    "sourceSkeleton": "/Game/_AnimDaily/ParkourAnimations/Characters/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 0.6667,
    "sourceDurationSeconds": 0.6667,
    "catalogDurationSeconds": 0.6667
  },
  {
    "id": "unreal-daily-roll-dodge-dash-forward",
    "clipName": "C57_unreal_daily_roll_dodge_dash_forward",
    "name": "向前冲刺",
    "actionType": "move",
    "classificationId": "dodge",
    "classificationLabel": "翻滚 / 闪避",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "dash-forward",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-roll-dodge",
    "packLabel": "翻滚闪避套装",
    "sourcePack": "RollDodgeDashSet",
    "sourceAssetPath": "/Game/_AnimDaily/RollDodgeDashSet/Animations/InPlace/Mannequin_UE4/Dash/A_INP_Dash_IdleFwd",
    "sourceAssetName": "A_INP_Dash_IdleFwd",
    "sourceSkeleton": "/Game/_AnimDaily/RollDodgeDashSet/Demo/Mannequin_UE4/Meshes/SK_Mannequin_Skeleton.SK_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 0.9333,
    "sourceDurationSeconds": 0.9333,
    "catalogDurationSeconds": 0.9333
  },
  {
    "id": "unreal-daily-dialogue-walk-in-place",
    "clipName": "C57_unreal_daily_dialogue_walk_in_place",
    "name": "对话移动",
    "actionType": "move",
    "classificationId": "dialogue",
    "classificationLabel": "对话 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "walk-in-place",
    "isIdleVariant": false,
    "groupId": "unreal-daily",
    "groupLabel": "日常动作",
    "packId": "unreal-daily-dialogue",
    "packLabel": "对话表演套装",
    "sourcePack": "Dialogue_mocap",
    "sourceAssetPath": "/Game/_AnimDaily/Dialogue_mocap/DEMO/Characters/Mannequins/Animations/Manny/MM_Walk_InPlace",
    "sourceAssetName": "MM_Walk_InPlace",
    "sourceSkeleton": "/Game/_AnimDaily/Dialogue_mocap/DEMO/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 2.7333,
    "sourceDurationSeconds": 2.7333,
    "catalogDurationSeconds": 2.7333
  },
  {
    "id": "unreal-misc-clazy-jog-forward",
    "clipName": "C57_unreal_misc_clazy_jog_forward",
    "name": "慢跑前进",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jog-forward",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_8way_Jog/Mvm_Jog_Fwd",
    "sourceAssetName": "Mvm_Jog_Fwd",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 0.9333,
    "sourceDurationSeconds": 0.9333,
    "catalogDurationSeconds": 0.9333
  },
  {
    "id": "unreal-misc-clazy-jog-backward",
    "clipName": "C57_unreal_misc_clazy_jog_backward",
    "name": "慢跑后退",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jog-backward",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_8way_Jog/Mvm_Jog_Bwd",
    "sourceAssetName": "Mvm_Jog_Bwd",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 0.9333,
    "sourceDurationSeconds": 0.9333,
    "catalogDurationSeconds": 0.9333
  },
  {
    "id": "unreal-misc-clazy-jog-start",
    "clipName": "C57_unreal_misc_clazy_jog_start",
    "name": "慢跑起步",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jog-start",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_8way_Jog_Start/Mvm_JogStart_Fwd",
    "sourceAssetName": "Mvm_JogStart_Fwd",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 0.5667,
    "sourceDurationSeconds": 0.5667,
    "catalogDurationSeconds": 0.5667
  },
  {
    "id": "unreal-misc-clazy-jog-stop",
    "clipName": "C57_unreal_misc_clazy_jog_stop",
    "name": "慢跑停止",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jog-stop",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_8way_Jog_Stop/Mvm_JogStop_Fwd",
    "sourceAssetName": "Mvm_JogStop_Fwd",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1,
    "sourceDurationSeconds": 1,
    "catalogDurationSeconds": 1
  },
  {
    "id": "unreal-misc-clazy-walk-forward",
    "clipName": "C57_unreal_misc_clazy_walk_forward",
    "name": "行走前进",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "walk-forward",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_8way_Walk/Mvm_Walk_Fwd",
    "sourceAssetName": "Mvm_Walk_Fwd",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.1333,
    "sourceDurationSeconds": 1.1333,
    "catalogDurationSeconds": 1.1333
  },
  {
    "id": "unreal-misc-clazy-walk-backward",
    "clipName": "C57_unreal_misc_clazy_walk_backward",
    "name": "行走后退",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "walk-backward",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_8way_Walk/Mvm_Walk_Bwd",
    "sourceAssetName": "Mvm_Walk_Bwd",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.1333,
    "sourceDurationSeconds": 1.1333,
    "catalogDurationSeconds": 1.1333
  },
  {
    "id": "unreal-misc-clazy-idle-a",
    "clipName": "C57_unreal_misc_clazy_idle_a",
    "name": "通用待机 A",
    "actionType": "idle",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:a",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P1-clazy-movement/Mvm_Idle/Mvm_IdleA",
    "sourceAssetName": "Mvm_IdleA",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-clazy-jump",
    "clipName": "C57_unreal_misc_clazy_jump",
    "name": "向上跳跃",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jump",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-clazy",
    "packLabel": "通用移动套装",
    "sourcePack": "CLazyAnimpack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CLazyAnimpack/Animations/P3-clazy-jump/Jmp_Air_Loop/Jump_Up_A_Loop",
    "sourceAssetName": "Jump_Up_A_Loop",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CLazyAnimpack/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 0.4,
    "sourceDurationSeconds": 0.4,
    "catalogDurationSeconds": 0.4
  },
  {
    "id": "unreal-misc-kawaii-barehands-idle",
    "clipName": "C57_unreal_misc_kawaii_barehands_idle",
    "name": "徒手战斗待机",
    "actionType": "idle",
    "classificationId": "barehand",
    "classificationLabel": "基础徒手",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "barehand",
    "weaponTypeLabel": "徒手",
    "dedupeKey": "idle:barehands",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-kawaii",
    "packLabel": "可爱战斗套装",
    "sourcePack": "KawaiiAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/KawaiiAnimations/Animations/Anim_KA_Combat_BareHands_Idle01",
    "sourceAssetName": "Anim_KA_Combat_BareHands_Idle01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/KawaiiAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 5,
    "sourceDurationSeconds": 5,
    "catalogDurationSeconds": 5
  },
  {
    "id": "unreal-misc-kawaii-heavy-sword-idle",
    "clipName": "C57_unreal_misc_kawaii_heavy_sword_idle",
    "name": "重剑战斗待机",
    "actionType": "idle",
    "classificationId": "sword",
    "classificationLabel": "剑",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "sword",
    "weaponTypeLabel": "剑",
    "dedupeKey": "idle:heavy-sword",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-kawaii",
    "packLabel": "可爱战斗套装",
    "sourcePack": "KawaiiAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/KawaiiAnimations/Animations/Anim_KA_Combat_HeavySword_Idle01",
    "sourceAssetName": "Anim_KA_Combat_HeavySword_Idle01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/KawaiiAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 3,
    "sourceDurationSeconds": 3,
    "catalogDurationSeconds": 3
  },
  {
    "id": "unreal-misc-kawaii-witch-idle",
    "clipName": "C57_unreal_misc_kawaii_witch_idle",
    "name": "女巫战斗待机",
    "actionType": "idle",
    "classificationId": "magic",
    "classificationLabel": "法术动作",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "magic",
    "weaponTypeLabel": "法术",
    "dedupeKey": "idle:witch",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-kawaii",
    "packLabel": "可爱战斗套装",
    "sourcePack": "KawaiiAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/KawaiiAnimations/Animations/Anim_KA_Combat_Witch_Idle01",
    "sourceAssetName": "Anim_KA_Combat_Witch_Idle01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/KawaiiAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 3,
    "sourceDurationSeconds": 3,
    "catalogDurationSeconds": 3
  },
  {
    "id": "unreal-misc-kawaii-witch-fly",
    "clipName": "C57_unreal_misc_kawaii_witch_fly",
    "name": "女巫飞行",
    "actionType": "magic",
    "classificationId": "magic",
    "classificationLabel": "法术动作",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "airborne",
    "postureLabel": "空中",
    "weaponType": "magic",
    "weaponTypeLabel": "法术",
    "dedupeKey": "witch-fly",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-kawaii",
    "packLabel": "可爱战斗套装",
    "sourcePack": "KawaiiAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/KawaiiAnimations/Animations/Anim_KA_Fly_Loop_Witch",
    "sourceAssetName": "Anim_KA_Fly_Loop_Witch",
    "sourceSkeleton": "/Game/_AnimDailyMisc/KawaiiAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-scared-standing-loop",
    "clipName": "C57_unreal_misc_scared_standing_loop",
    "name": "站立求饶",
    "actionType": "reaction",
    "classificationId": "reaction",
    "classificationLabel": "反应 / 求饶",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "standing-loop",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-scared",
    "packLabel": "惊恐反应套装",
    "sourcePack": "Scared_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Scared_01/Animation/In_Place/SCR_Beg_For_Life_Standing_Loop_IP",
    "sourceAssetName": "SCR_Beg_For_Life_Standing_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Scared_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 9.3667,
    "sourceDurationSeconds": 9.3667,
    "catalogDurationSeconds": 9.3667
  },
  {
    "id": "unreal-misc-scared-crouching-loop",
    "clipName": "C57_unreal_misc_scared_crouching_loop",
    "name": "蹲伏求饶",
    "actionType": "reaction",
    "classificationId": "crouching",
    "classificationLabel": "蹲伏",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "crouching",
    "postureLabel": "蹲伏",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "crouching-loop",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-scared",
    "packLabel": "惊恐反应套装",
    "sourcePack": "Scared_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Scared_01/Animation/In_Place/SCR_Beg_For_Life_Crouching_Loop_IP",
    "sourceAssetName": "SCR_Beg_For_Life_Crouching_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Scared_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 4.5,
    "sourceDurationSeconds": 4.5,
    "catalogDurationSeconds": 4.5
  },
  {
    "id": "unreal-misc-scared-creeping",
    "clipName": "C57_unreal_misc_scared_creeping",
    "name": "惊恐爬行",
    "actionType": "move",
    "classificationId": "ground-action",
    "classificationLabel": "地面动作",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "crawling",
    "postureLabel": "爬行",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "creeping",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-scared",
    "packLabel": "惊恐反应套装",
    "sourcePack": "Scared_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Scared_01/Animation/In_Place/SCR_Creeping_Fwd_Loop_IP",
    "sourceAssetName": "SCR_Creeping_Fwd_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Scared_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 6.7333,
    "sourceDurationSeconds": 6.7333,
    "catalogDurationSeconds": 6.7333
  },
  {
    "id": "unreal-misc-scared-hands-up",
    "clipName": "C57_unreal_misc_scared_hands_up",
    "name": "被威胁举手",
    "actionType": "reaction",
    "classificationId": "reaction",
    "classificationLabel": "反应 / 求饶",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "hands-up",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-scared",
    "packLabel": "惊恐反应套装",
    "sourcePack": "Scared_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Scared_01/Animation/In_Place/SCR_Gunpoint_Hands_Up_Loop_IP",
    "sourceAssetName": "SCR_Gunpoint_Hands_Up_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Scared_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 11.5333,
    "sourceDurationSeconds": 11.5333,
    "catalogDurationSeconds": 11.5333
  },
  {
    "id": "unreal-misc-scared-knees-hands-head",
    "clipName": "C57_unreal_misc_scared_knees_hands_head",
    "name": "跪地抱头",
    "actionType": "reaction",
    "classificationId": "kneeling",
    "classificationLabel": "跪姿",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "kneeling",
    "postureLabel": "跪姿",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "knees-hands-head",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-scared",
    "packLabel": "惊恐反应套装",
    "sourcePack": "Scared_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Scared_01/Animation/In_Place/SCR_Gunpoint_On_Knees_Hands_On_Head_Loop_IP",
    "sourceAssetName": "SCR_Gunpoint_On_Knees_Hands_On_Head_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Scared_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 7.9667,
    "sourceDurationSeconds": 7.9667,
    "catalogDurationSeconds": 7.9667
  },
  {
    "id": "unreal-misc-scared-runaway",
    "clipName": "C57_unreal_misc_scared_runaway",
    "name": "惊慌逃跑",
    "actionType": "move",
    "classificationId": "reaction",
    "classificationLabel": "反应 / 求饶",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "runaway",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-scared",
    "packLabel": "惊恐反应套装",
    "sourcePack": "Scared_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Scared_01/Animation/In_Place/SCR_Runaway_Run_Loop_IP",
    "sourceAssetName": "SCR_Runaway_Run_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Scared_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1.7333,
    "sourceDurationSeconds": 1.7333,
    "catalogDurationSeconds": 1.7333
  },
  {
    "id": "unreal-misc-morbid-idle-a",
    "clipName": "C57_unreal_misc_morbid_idle_a",
    "name": "惊悚待机 A",
    "actionType": "idle",
    "classificationId": "monster",
    "classificationLabel": "怪物动作",
    "actorKind": "monster",
    "actorKindLabel": "怪物",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:a",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-morbid",
    "packLabel": "惊悚变异套装",
    "sourcePack": "MorbidMotions_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Animations_Vol2/30fps/ANIM_idle_A",
    "sourceAssetName": "ANIM_idle_A",
    "sourceSkeleton": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.4,
    "sourceDurationSeconds": 1.4,
    "catalogDurationSeconds": 1.4
  },
  {
    "id": "unreal-misc-morbid-idle-b",
    "clipName": "C57_unreal_misc_morbid_idle_b",
    "name": "惊悚待机 B",
    "actionType": "idle",
    "classificationId": "monster",
    "classificationLabel": "怪物动作",
    "actorKind": "monster",
    "actorKindLabel": "怪物",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:b",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-morbid",
    "packLabel": "惊悚变异套装",
    "sourcePack": "MorbidMotions_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Animations_Vol2/30fps/ANIM_idle_B",
    "sourceAssetName": "ANIM_idle_B",
    "sourceSkeleton": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 3,
    "sourceDurationSeconds": 3,
    "catalogDurationSeconds": 3
  },
  {
    "id": "unreal-misc-morbid-tied-idle",
    "clipName": "C57_unreal_misc_morbid_tied_idle",
    "name": "束缚待机",
    "actionType": "idle",
    "classificationId": "monster",
    "classificationLabel": "怪物动作",
    "actorKind": "monster",
    "actorKindLabel": "怪物",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:tied",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-morbid",
    "packLabel": "惊悚变异套装",
    "sourcePack": "MorbidMotions_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Animations_Vol2/30fps/ANIM_Tied_idle",
    "sourceAssetName": "ANIM_Tied_idle",
    "sourceSkeleton": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-morbid-tied-escape",
    "clipName": "C57_unreal_misc_morbid_tied_escape",
    "name": "束缚挣扎",
    "actionType": "reaction",
    "classificationId": "monster",
    "classificationLabel": "怪物动作",
    "actorKind": "monster",
    "actorKindLabel": "怪物",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "tied-escape",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-morbid",
    "packLabel": "惊悚变异套装",
    "sourcePack": "MorbidMotions_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Animations_Vol2/30fps/ANIM_TiedSit_try_escape",
    "sourceAssetName": "ANIM_TiedSit_try_escape",
    "sourceSkeleton": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 5.3333,
    "sourceDurationSeconds": 5.3333,
    "catalogDurationSeconds": 5.3333
  },
  {
    "id": "unreal-misc-morbid-transform",
    "clipName": "C57_unreal_misc_morbid_transform",
    "name": "变异待机",
    "actionType": "combat",
    "classificationId": "monster",
    "classificationLabel": "怪物动作",
    "actorKind": "monster",
    "actorKindLabel": "怪物",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "transform",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-morbid",
    "packLabel": "惊悚变异套装",
    "sourcePack": "MorbidMotions_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Animations_Vol2/30fps/ANIM_Transform_idle_A",
    "sourceAssetName": "ANIM_Transform_idle_A",
    "sourceSkeleton": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2.1667,
    "sourceDurationSeconds": 2.1667,
    "catalogDurationSeconds": 2.1667
  },
  {
    "id": "unreal-misc-morbid-emerge",
    "clipName": "C57_unreal_misc_morbid_emerge",
    "name": "从地面出现",
    "actionType": "daily",
    "classificationId": "ground-action",
    "classificationLabel": "地面动作",
    "actorKind": "monster",
    "actorKindLabel": "怪物",
    "posture": "lying",
    "postureLabel": "躺卧",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "emerge",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-morbid",
    "packLabel": "惊悚变异套装",
    "sourcePack": "MorbidMotions_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Animations_Vol2/30fps/ANIM_emerge_A_to_idle_A",
    "sourceAssetName": "ANIM_emerge_A_to_idle_A",
    "sourceSkeleton": "/Game/_AnimDailyMisc/MorbidMotions_Pack/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 3,
    "sourceDurationSeconds": 3,
    "catalogDurationSeconds": 3
  },
  {
    "id": "unreal-misc-taunts-arm-cross",
    "clipName": "C57_unreal_misc_taunts_arm_cross",
    "name": "抱臂挑衅",
    "actionType": "idle",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:arms-cross",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Loops/Ani_armCrossLoop_01",
    "sourceAssetName": "Ani_armCrossLoop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.9667,
    "sourceDurationSeconds": 1.9667,
    "catalogDurationSeconds": 1.9667
  },
  {
    "id": "unreal-misc-taunts-wave",
    "clipName": "C57_unreal_misc_taunts_wave",
    "name": "挥手",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "wave",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Ani_wave_01",
    "sourceAssetName": "Ani_wave_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-taunts-hand-punch",
    "clipName": "C57_unreal_misc_taunts_hand_punch",
    "name": "手部出拳",
    "actionType": "boxing",
    "classificationId": "barehand",
    "classificationLabel": "基础徒手",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "barehand",
    "weaponTypeLabel": "徒手",
    "dedupeKey": "hand-punch",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Ani_handPunch_01",
    "sourceAssetName": "Ani_handPunch_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2.4667,
    "sourceDurationSeconds": 2.4667,
    "catalogDurationSeconds": 2.4667
  },
  {
    "id": "unreal-misc-taunts-come-get-me",
    "clipName": "C57_unreal_misc_taunts_come_get_me",
    "name": "招手挑衅",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "come-get-me",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Loops/Ani_comeGetMeLoop_01",
    "sourceAssetName": "Ani_comeGetMeLoop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.9667,
    "sourceDurationSeconds": 1.9667,
    "catalogDurationSeconds": 1.9667
  },
  {
    "id": "unreal-misc-taunts-finger-gun",
    "clipName": "C57_unreal_misc_taunts_finger_gun",
    "name": "手指枪",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "finger-gun",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Loops/Ani_fingerGunLoop_01",
    "sourceAssetName": "Ani_fingerGunLoop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.9667,
    "sourceDurationSeconds": 1.9667,
    "catalogDurationSeconds": 1.9667
  },
  {
    "id": "unreal-misc-taunts-fist-pump",
    "clipName": "C57_unreal_misc_taunts_fist_pump",
    "name": "挥拳庆祝",
    "actionType": "boxing",
    "classificationId": "barehand",
    "classificationLabel": "基础徒手",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "barehand",
    "weaponTypeLabel": "徒手",
    "dedupeKey": "fist-pump",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Loops/Ani_fistPumpLoop_01",
    "sourceAssetName": "Ani_fistPumpLoop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.9667,
    "sourceDurationSeconds": 1.9667,
    "catalogDurationSeconds": 1.9667
  },
  {
    "id": "unreal-misc-taunts-flex",
    "clipName": "C57_unreal_misc_taunts_flex",
    "name": "展示肌肉",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "flex",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-taunts",
    "packLabel": "挑衅手势套装",
    "sourcePack": "TauntsPack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/TauntsPack/Animations/Taunts/Loops/Ani_flexLoop_01",
    "sourceAssetName": "Ani_flexLoop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/TauntsPack/Meshes/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.9667,
    "sourceDurationSeconds": 1.9667,
    "catalogDurationSeconds": 1.9667
  },
  {
    "id": "unreal-misc-couples-arms-around-loop-att",
    "clipName": "C57_unreal_misc_couples_arms_around_loop_att",
    "name": "搭肩互动 · 主动方",
    "actionType": "paired",
    "classificationId": "paired",
    "classificationLabel": "配对互动",
    "actorKind": "paired",
    "actorKindLabel": "配对角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "arms-around-loop-att",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-couples",
    "packLabel": "配对互动套装",
    "sourcePack": "Couples_Anim_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Couples_Anim_Pack/Animations/AnimSeq_Paired_Couple_ArmsAroundShoulder_Loop_Att",
    "sourceAssetName": "AnimSeq_Paired_Couple_ArmsAroundShoulder_Loop_Att",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Couples_Anim_Pack/Demo/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.6667,
    "sourceDurationSeconds": 1.6667,
    "catalogDurationSeconds": 1.6667
  },
  {
    "id": "unreal-misc-couples-back-hug-loop-att",
    "clipName": "C57_unreal_misc_couples_back_hug_loop_att",
    "name": "背后拥抱 · 主动方",
    "actionType": "paired",
    "classificationId": "paired",
    "classificationLabel": "配对互动",
    "actorKind": "paired",
    "actorKindLabel": "配对角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "back-hug-loop-att",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-couples",
    "packLabel": "配对互动套装",
    "sourcePack": "Couples_Anim_Pack",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Couples_Anim_Pack/Animations/AnimSeq_Paired_Couple_BackHug_Loop_Att",
    "sourceAssetName": "AnimSeq_Paired_Couple_BackHug_Loop_Att",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Couples_Anim_Pack/Demo/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-crowd-cheer",
    "clipName": "C57_unreal_misc_crowd_cheer",
    "name": "欢呼",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "cheer",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-crowd",
    "packLabel": "群演手势套装",
    "sourcePack": "CrowdAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CrowdAnimations/Animation/A_Chear_Loop_01",
    "sourceAssetName": "A_Chear_Loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CrowdAnimations/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-crowd-lean-forward",
    "clipName": "C57_unreal_misc_crowd_lean_forward",
    "name": "前倾观察",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "lean-forward",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-crowd",
    "packLabel": "群演手势套装",
    "sourcePack": "CrowdAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CrowdAnimations/Animation/A_leanforward_Loop_01",
    "sourceAssetName": "A_leanforward_Loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CrowdAnimations/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-crowd-metal",
    "clipName": "C57_unreal_misc_crowd_metal",
    "name": "摇摆应援",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "metal",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-crowd",
    "packLabel": "群演手势套装",
    "sourcePack": "CrowdAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CrowdAnimations/Animation/A_Metal_Loop_01",
    "sourceAssetName": "A_Metal_Loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CrowdAnimations/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-crowd-point",
    "clipName": "C57_unreal_misc_crowd_point",
    "name": "指向",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "point",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-crowd",
    "packLabel": "群演手势套装",
    "sourcePack": "CrowdAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CrowdAnimations/Animation/A_Point_Loop_01",
    "sourceAssetName": "A_Point_Loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CrowdAnimations/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.3333,
    "sourceDurationSeconds": 1.3333,
    "catalogDurationSeconds": 1.3333
  },
  {
    "id": "unreal-misc-crowd-thumbs-up",
    "clipName": "C57_unreal_misc_crowd_thumbs_up",
    "name": "群演点赞",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "thumbs-up",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-crowd",
    "packLabel": "群演手势套装",
    "sourcePack": "CrowdAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/CrowdAnimations/Animation/A_thumbsUp_loop_01",
    "sourceAssetName": "A_thumbsUp_loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/CrowdAnimations/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 3.3333,
    "sourceDurationSeconds": 3.3333,
    "catalogDurationSeconds": 3.3333
  },
  {
    "id": "unreal-misc-pedestrian-walks-relaxed",
    "clipName": "C57_unreal_misc_pedestrian_walks_relaxed",
    "name": "放松行走",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "relaxed",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-pedestrian-walks",
    "packLabel": "行人步态套装",
    "sourcePack": "Pedestrian_Walks_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Animation/In_Place/Walk_01_Relaxed_Loop_IP",
    "sourceAssetName": "Walk_01_Relaxed_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1.1333,
    "sourceDurationSeconds": 1.1333,
    "catalogDurationSeconds": 1.1333
  },
  {
    "id": "unreal-misc-pedestrian-walks-cheerful",
    "clipName": "C57_unreal_misc_pedestrian_walks_cheerful",
    "name": "愉快行走",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "cheerful",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-pedestrian-walks",
    "packLabel": "行人步态套装",
    "sourcePack": "Pedestrian_Walks_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Animation/In_Place/Walk_02_Cheerful_Loop_IP",
    "sourceAssetName": "Walk_02_Cheerful_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1.2,
    "sourceDurationSeconds": 1.2,
    "catalogDurationSeconds": 1.2
  },
  {
    "id": "unreal-misc-pedestrian-walks-mad",
    "clipName": "C57_unreal_misc_pedestrian_walks_mad",
    "name": "生气行走",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "mad",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-pedestrian-walks",
    "packLabel": "行人步态套装",
    "sourcePack": "Pedestrian_Walks_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Animation/In_Place/Walk_03_Mad_Loop_IP",
    "sourceAssetName": "Walk_03_Mad_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 7.3,
    "sourceDurationSeconds": 7.3,
    "catalogDurationSeconds": 7.3
  },
  {
    "id": "unreal-misc-pedestrian-walks-texting",
    "clipName": "C57_unreal_misc_pedestrian_walks_texting",
    "name": "边走边发消息",
    "actionType": "daily",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "texting",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-pedestrian-walks",
    "packLabel": "行人步态套装",
    "sourcePack": "Pedestrian_Walks_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Animation/In_Place/Walk_04_Texting_Loop_IP",
    "sourceAssetName": "Walk_04_Texting_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 3.3,
    "sourceDurationSeconds": 3.3,
    "catalogDurationSeconds": 3.3
  },
  {
    "id": "unreal-misc-pedestrian-walks-phone-call",
    "clipName": "C57_unreal_misc_pedestrian_walks_phone_call",
    "name": "边走边打电话",
    "actionType": "daily",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "phone-call",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-pedestrian-walks",
    "packLabel": "行人步态套装",
    "sourcePack": "Pedestrian_Walks_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Animation/In_Place/Walk_05_Phone_Call_Loop_IP",
    "sourceAssetName": "Walk_05_Phone_Call_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 3.2667,
    "sourceDurationSeconds": 3.2667,
    "catalogDurationSeconds": 3.2667
  },
  {
    "id": "unreal-misc-pedestrian-walks-running-late",
    "clipName": "C57_unreal_misc_pedestrian_walks_running_late",
    "name": "迟到奔跑",
    "actionType": "move",
    "classificationId": "locomotion",
    "classificationLabel": "站立移动",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "running-late",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-pedestrian-walks",
    "packLabel": "行人步态套装",
    "sourcePack": "Pedestrian_Walks_01",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Animation/In_Place/Walk_10_Running_Late_Loop_IP",
    "sourceAssetName": "Walk_10_Running_Late_Loop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Pedestrian_Walks_01/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 8.0333,
    "sourceDurationSeconds": 8.0333,
    "catalogDurationSeconds": 8.0333
  },
  {
    "id": "unreal-misc-climbing-climbing-idle",
    "clipName": "C57_unreal_misc_climbing_climbing_idle",
    "name": "攀爬待机",
    "actionType": "idle",
    "classificationId": "climbing",
    "classificationLabel": "攀爬",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:climbing",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-climbing",
    "packLabel": "攀爬墙面套装",
    "sourcePack": "ClimbingAnimationSet",
    "sourceAssetPath": "/Game/_AnimDailyMisc/ClimbingAnimationSet/Animations/InPlace/Climbing_Idle_IP",
    "sourceAssetName": "Climbing_Idle_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/ClimbingAnimationSet/DemoAssets/Characters/Mannequin/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 2.6667,
    "sourceDurationSeconds": 2.6667,
    "catalogDurationSeconds": 2.6667
  },
  {
    "id": "unreal-misc-climbing-climb-up",
    "clipName": "C57_unreal_misc_climbing_climb_up",
    "name": "向上攀爬",
    "actionType": "parkour",
    "classificationId": "climbing",
    "classificationLabel": "攀爬",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "climb-up",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-climbing",
    "packLabel": "攀爬墙面套装",
    "sourcePack": "ClimbingAnimationSet",
    "sourceAssetPath": "/Game/_AnimDailyMisc/ClimbingAnimationSet/Animations/InPlace/Climbing_Climb_U_IP",
    "sourceAssetName": "Climbing_Climb_U_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/ClimbingAnimationSet/DemoAssets/Characters/Mannequin/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1,
    "sourceDurationSeconds": 1,
    "catalogDurationSeconds": 1
  },
  {
    "id": "unreal-misc-climbing-climb-left",
    "clipName": "C57_unreal_misc_climbing_climb_left",
    "name": "向左攀爬",
    "actionType": "parkour",
    "classificationId": "climbing",
    "classificationLabel": "攀爬",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "climb-left",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-climbing",
    "packLabel": "攀爬墙面套装",
    "sourcePack": "ClimbingAnimationSet",
    "sourceAssetPath": "/Game/_AnimDailyMisc/ClimbingAnimationSet/Animations/InPlace/Climbing_Climb_L_IP",
    "sourceAssetName": "Climbing_Climb_L_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/ClimbingAnimationSet/DemoAssets/Characters/Mannequin/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1,
    "sourceDurationSeconds": 1,
    "catalogDurationSeconds": 1
  },
  {
    "id": "unreal-misc-climbing-climb-right",
    "clipName": "C57_unreal_misc_climbing_climb_right",
    "name": "向右攀爬",
    "actionType": "parkour",
    "classificationId": "climbing",
    "classificationLabel": "攀爬",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "climb-right",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-climbing",
    "packLabel": "攀爬墙面套装",
    "sourcePack": "ClimbingAnimationSet",
    "sourceAssetPath": "/Game/_AnimDailyMisc/ClimbingAnimationSet/Animations/InPlace/Climbing_Climb_R_IP",
    "sourceAssetName": "Climbing_Climb_R_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/ClimbingAnimationSet/DemoAssets/Characters/Mannequin/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1,
    "sourceDurationSeconds": 1,
    "catalogDurationSeconds": 1
  },
  {
    "id": "unreal-misc-climbing-drop",
    "clipName": "C57_unreal_misc_climbing_drop",
    "name": "攀爬下落",
    "actionType": "parkour",
    "classificationId": "climbing",
    "classificationLabel": "攀爬",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "drop",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-climbing",
    "packLabel": "攀爬墙面套装",
    "sourcePack": "ClimbingAnimationSet",
    "sourceAssetPath": "/Game/_AnimDailyMisc/ClimbingAnimationSet/Animations/InPlace/Climbing_Drop_IP",
    "sourceAssetName": "Climbing_Drop_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/ClimbingAnimationSet/DemoAssets/Characters/Mannequin/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1.25,
    "sourceDurationSeconds": 1.25,
    "catalogDurationSeconds": 1.25
  },
  {
    "id": "unreal-misc-climbing-jump-out",
    "clipName": "C57_unreal_misc_climbing_jump_out",
    "name": "攀爬跳离",
    "actionType": "parkour",
    "classificationId": "climbing",
    "classificationLabel": "攀爬",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jump-out",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-climbing",
    "packLabel": "攀爬墙面套装",
    "sourcePack": "ClimbingAnimationSet",
    "sourceAssetPath": "/Game/_AnimDailyMisc/ClimbingAnimationSet/Animations/InPlace/Climbing_Jump_Out_IP",
    "sourceAssetName": "Climbing_Jump_Out_IP",
    "sourceSkeleton": "/Game/_AnimDailyMisc/ClimbingAnimationSet/DemoAssets/Characters/Mannequin/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "source-path",
    "durationSeconds": 1.5833,
    "sourceDurationSeconds": 1.5833,
    "catalogDurationSeconds": 1.5833
  },
  {
    "id": "unreal-misc-irap-injured-front-idle",
    "clipName": "C57_unreal_misc_irap_injured_front_idle",
    "name": "正面受伤待机",
    "actionType": "idle",
    "classificationId": "injury-recovery",
    "classificationLabel": "受伤 / 恢复",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:injured-front",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-irap",
    "packLabel": "受伤与恢复套装",
    "sourcePack": "IRAP",
    "sourceAssetPath": "/Game/_AnimDailyMisc/IRAP/Animations/Front_Injured_Idle",
    "sourceAssetName": "Front_Injured_Idle",
    "sourceSkeleton": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2.9,
    "sourceDurationSeconds": 2.9,
    "catalogDurationSeconds": 2.9
  },
  {
    "id": "unreal-misc-irap-injured-back-idle",
    "clipName": "C57_unreal_misc_irap_injured_back_idle",
    "name": "背面受伤待机",
    "actionType": "idle",
    "classificationId": "injury-recovery",
    "classificationLabel": "受伤 / 恢复",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:injured-back",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-irap",
    "packLabel": "受伤与恢复套装",
    "sourcePack": "IRAP",
    "sourceAssetPath": "/Game/_AnimDailyMisc/IRAP/Animations/Back_Injured_Idle",
    "sourceAssetName": "Back_Injured_Idle",
    "sourceSkeleton": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.5,
    "sourceDurationSeconds": 1.5,
    "catalogDurationSeconds": 1.5
  },
  {
    "id": "unreal-misc-irap-injured-walk",
    "clipName": "C57_unreal_misc_irap_injured_walk",
    "name": "受伤行走",
    "actionType": "move",
    "classificationId": "injury-recovery",
    "classificationLabel": "受伤 / 恢复",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "injured-walk",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-irap",
    "packLabel": "受伤与恢复套装",
    "sourcePack": "IRAP",
    "sourceAssetPath": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Animations/ThirdPersonWalk",
    "sourceAssetName": "ThirdPersonWalk",
    "sourceSkeleton": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1,
    "sourceDurationSeconds": 1,
    "catalogDurationSeconds": 1
  },
  {
    "id": "unreal-misc-irap-injured-run",
    "clipName": "C57_unreal_misc_irap_injured_run",
    "name": "受伤奔跑",
    "actionType": "move",
    "classificationId": "injury-recovery",
    "classificationLabel": "受伤 / 恢复",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "injured-run",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-irap",
    "packLabel": "受伤与恢复套装",
    "sourcePack": "IRAP",
    "sourceAssetPath": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Animations/ThirdPersonRun",
    "sourceAssetName": "ThirdPersonRun",
    "sourceSkeleton": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 0.6,
    "sourceDurationSeconds": 0.6,
    "catalogDurationSeconds": 0.6
  },
  {
    "id": "unreal-misc-irap-jump",
    "clipName": "C57_unreal_misc_irap_jump",
    "name": "受伤跳跃起步",
    "actionType": "move",
    "classificationId": "injury-recovery",
    "classificationLabel": "受伤 / 恢复",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "jump",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-irap",
    "packLabel": "受伤与恢复套装",
    "sourcePack": "IRAP",
    "sourceAssetPath": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Animations/ThirdPersonJump_Start",
    "sourceAssetName": "ThirdPersonJump_Start",
    "sourceSkeleton": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 0.4667,
    "sourceDurationSeconds": 0.4667,
    "catalogDurationSeconds": 0.4667
  },
  {
    "id": "unreal-misc-irap-revive",
    "clipName": "C57_unreal_misc_irap_revive",
    "name": "倒地恢复",
    "actionType": "reaction",
    "classificationId": "injury-recovery",
    "classificationLabel": "受伤 / 恢复",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "revive",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-irap",
    "packLabel": "受伤与恢复套装",
    "sourcePack": "IRAP",
    "sourceAssetPath": "/Game/_AnimDailyMisc/IRAP/Animations/Back_Revive",
    "sourceAssetName": "Back_Revive",
    "sourceSkeleton": "/Game/_AnimDailyMisc/IRAP/EpicContent/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 4.2917,
    "sourceDurationSeconds": 4.2917,
    "catalogDurationSeconds": 4.2917
  },
  {
    "id": "unreal-misc-preacher-idle",
    "clipName": "C57_unreal_misc_preacher_idle",
    "name": "演讲待机",
    "actionType": "idle",
    "classificationId": "prayer-speech",
    "classificationLabel": "祈祷 / 演讲",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:preacher",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-preacher",
    "packLabel": "祈祷演讲套装",
    "sourcePack": "PreacherAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/PreacherAnimations/Animations/Idle/ANIM_IP_idle_01",
    "sourceAssetName": "ANIM_IP_idle_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/PreacherAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 46.9333,
    "sourceDurationSeconds": 46.9333,
    "catalogDurationSeconds": 46.9333
  },
  {
    "id": "unreal-misc-preacher-pray-ground",
    "clipName": "C57_unreal_misc_preacher_pray_ground",
    "name": "跪地祈祷",
    "actionType": "performance",
    "classificationId": "prayer-speech",
    "classificationLabel": "祈祷 / 演讲",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "kneeling",
    "postureLabel": "跪姿",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "pray-ground",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-preacher",
    "packLabel": "祈祷演讲套装",
    "sourcePack": "PreacherAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/PreacherAnimations/Animations/Pray/ANIM_IP_pray_ground_loop_01",
    "sourceAssetName": "ANIM_IP_pray_ground_loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/PreacherAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 2,
    "sourceDurationSeconds": 2,
    "catalogDurationSeconds": 2
  },
  {
    "id": "unreal-misc-preacher-pray-standing",
    "clipName": "C57_unreal_misc_preacher_pray_standing",
    "name": "站立祈祷",
    "actionType": "performance",
    "classificationId": "prayer-speech",
    "classificationLabel": "祈祷 / 演讲",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "pray-standing",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-preacher",
    "packLabel": "祈祷演讲套装",
    "sourcePack": "PreacherAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/PreacherAnimations/Animations/Pray/ANIM_IP_standing_pray_loop_01",
    "sourceAssetName": "ANIM_IP_standing_pray_loop_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/PreacherAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 8.3333,
    "sourceDurationSeconds": 8.3333,
    "catalogDurationSeconds": 8.3333
  },
  {
    "id": "unreal-misc-preacher-complain",
    "clipName": "C57_unreal_misc_preacher_complain",
    "name": "站立演讲",
    "actionType": "performance",
    "classificationId": "prayer-speech",
    "classificationLabel": "祈祷 / 演讲",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "complain",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-preacher",
    "packLabel": "祈祷演讲套装",
    "sourcePack": "PreacherAnimations",
    "sourceAssetPath": "/Game/_AnimDailyMisc/PreacherAnimations/Animations/Pray/ANIM_IP_standing_complain",
    "sourceAssetName": "ANIM_IP_standing_complain",
    "sourceSkeleton": "/Game/_AnimDailyMisc/PreacherAnimations/Demo/Characters/Mannequins/Meshes/SK_Mannequin.SK_Mannequin",
    "inPlace": true,
    "inPlaceEvidence": "asset-name",
    "durationSeconds": 30.1,
    "sourceDurationSeconds": 30.1,
    "catalogDurationSeconds": 30.1
  },
  {
    "id": "unreal-misc-supporter-supporter-01",
    "clipName": "C57_unreal_misc_supporter_supporter_01",
    "name": "助威动作 1",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "supporter-01",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-supporter",
    "packLabel": "助威动作套装",
    "sourcePack": "suppoter_motion",
    "sourceAssetPath": "/Game/_AnimDailyMisc/suppoter_motion/animation/spo_01",
    "sourceAssetName": "spo_01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/suppoter_motion/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.7667,
    "sourceDurationSeconds": 1.7667,
    "catalogDurationSeconds": 1.7667
  },
  {
    "id": "unreal-misc-supporter-supporter-02",
    "clipName": "C57_unreal_misc_supporter_supporter_02",
    "name": "助威动作 2",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "supporter-02",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-supporter",
    "packLabel": "助威动作套装",
    "sourcePack": "suppoter_motion",
    "sourceAssetPath": "/Game/_AnimDailyMisc/suppoter_motion/animation/spo_02",
    "sourceAssetName": "spo_02",
    "sourceSkeleton": "/Game/_AnimDailyMisc/suppoter_motion/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2.5333,
    "sourceDurationSeconds": 2.5333,
    "catalogDurationSeconds": 2.5333
  },
  {
    "id": "unreal-misc-supporter-supporter-ad-01",
    "clipName": "C57_unreal_misc_supporter_supporter_ad_01",
    "name": "广告助威动作",
    "actionType": "performance",
    "classificationId": "performance",
    "classificationLabel": "表演 / 手势",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "standing",
    "postureLabel": "站立",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "supporter-ad-01",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-supporter",
    "packLabel": "助威动作套装",
    "sourcePack": "suppoter_motion",
    "sourceAssetPath": "/Game/_AnimDailyMisc/suppoter_motion/animation/spo_ad01",
    "sourceAssetName": "spo_ad01",
    "sourceSkeleton": "/Game/_AnimDailyMisc/suppoter_motion/Mannequin/Character/Mesh/UE4_Mannequin_Skeleton.UE4_Mannequin_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 2.6333,
    "sourceDurationSeconds": 2.6333,
    "catalogDurationSeconds": 2.6333
  },
  {
    "id": "unreal-misc-female-mocap-stand-idle",
    "clipName": "C57_unreal_misc_female_mocap_stand_idle",
    "name": "女性站立待机",
    "actionType": "idle",
    "classificationId": "performance",
    "classificationLabel": "生活 / 表演",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:stand",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-female-mocap",
    "packLabel": "女性生活表演套装",
    "sourcePack": "Female_Mocap_AnimPackVol1",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/AnimationsSouce/Anim_FemaleVol1_StandIdle02Loop",
    "sourceAssetName": "Anim_FemaleVol1_StandIdle02Loop",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/demo/Mesh/SK_Mannequin_Female_Skeleton.SK_Mannequin_Female_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 4.5667,
    "sourceDurationSeconds": 4.5667,
    "catalogDurationSeconds": 4.5667
  },
  {
    "id": "unreal-misc-female-mocap-stand-variant",
    "clipName": "C57_unreal_misc_female_mocap_stand_variant",
    "name": "女性站立待机 · 变体",
    "actionType": "idle",
    "classificationId": "performance",
    "classificationLabel": "生活 / 表演",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "idle:stand-variant",
    "isIdleVariant": true,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-female-mocap",
    "packLabel": "女性生活表演套装",
    "sourcePack": "Female_Mocap_AnimPackVol1",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/AnimationsSouce/Anim_FemaleVol1_Stand01Loop",
    "sourceAssetName": "Anim_FemaleVol1_Stand01Loop",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/demo/Mesh/SK_Mannequin_Female_Skeleton.SK_Mannequin_Female_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 3.3,
    "sourceDurationSeconds": 3.3,
    "catalogDurationSeconds": 3.3
  },
  {
    "id": "unreal-misc-female-mocap-sit-idle",
    "clipName": "C57_unreal_misc_female_mocap_sit_idle",
    "name": "女性坐姿待机",
    "actionType": "sit",
    "classificationId": "sitting",
    "classificationLabel": "坐姿",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "sitting",
    "postureLabel": "坐姿",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "sit-idle",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-female-mocap",
    "packLabel": "女性生活表演套装",
    "sourcePack": "Female_Mocap_AnimPackVol1",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/AnimationsSouce/Anim_FemaleVol1_SitIdleLoop",
    "sourceAssetName": "Anim_FemaleVol1_SitIdleLoop",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/demo/Mesh/SK_Mannequin_Female_Skeleton.SK_Mannequin_Female_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 7.3333,
    "sourceDurationSeconds": 7.3333,
    "catalogDurationSeconds": 7.3333
  },
  {
    "id": "unreal-misc-female-mocap-play-water",
    "clipName": "C57_unreal_misc_female_mocap_play_water",
    "name": "玩水",
    "actionType": "daily",
    "classificationId": "performance",
    "classificationLabel": "生活 / 表演",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "play-water",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-female-mocap",
    "packLabel": "女性生活表演套装",
    "sourcePack": "Female_Mocap_AnimPackVol1",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/AnimationsSouce/Anim_FemaleVol1_PlayWater01Loop",
    "sourceAssetName": "Anim_FemaleVol1_PlayWater01Loop",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/demo/Mesh/SK_Mannequin_Female_Skeleton.SK_Mannequin_Female_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 6.7333,
    "sourceDurationSeconds": 6.7333,
    "catalogDurationSeconds": 6.7333
  },
  {
    "id": "unreal-misc-female-mocap-walk",
    "clipName": "C57_unreal_misc_female_mocap_walk",
    "name": "女性行走",
    "actionType": "move",
    "classificationId": "performance",
    "classificationLabel": "生活 / 表演",
    "actorKind": "human",
    "actorKindLabel": "人形角色",
    "posture": "mixed",
    "postureLabel": "综合姿态",
    "weaponType": "none",
    "weaponTypeLabel": "无武器",
    "dedupeKey": "walk",
    "isIdleVariant": false,
    "groupId": "unreal-misc",
    "groupLabel": "生活与表演",
    "packId": "unreal-misc-female-mocap",
    "packLabel": "女性生活表演套装",
    "sourcePack": "Female_Mocap_AnimPackVol1",
    "sourceAssetPath": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/AnimationsSouce/Anim_FemaleVol1_WalkLoop",
    "sourceAssetName": "Anim_FemaleVol1_WalkLoop",
    "sourceSkeleton": "/Game/_AnimDailyMisc/Female_Mocap_AnimPackVol1/demo/Mesh/SK_Mannequin_Female_Skeleton.SK_Mannequin_Female_Skeleton",
    "inPlace": true,
    "inPlaceEvidence": "unmarked-non-root",
    "durationSeconds": 1.4,
    "sourceDurationSeconds": 1.4,
    "catalogDurationSeconds": 1.4
  }
] as const;
