/**
 * 模型库目录：内置常用模型的静态清单。
 *
 * 模型文件放在 client/public/models/ 下由前端静态服务；目录只是数据，
 * 不做任何运行时探测。数据来自 Cine57（UE 5.7）经 FBX + FBX2glTF 的
 * 导出管线（见 docs/wiki/product/model-library.md），几何单位已是米。
 * materials 把 FBX 带出的材质资源名映射到真实贴图，运行时由
 * modelLibrary3d/modelMaterials.ts 回填到 PlayCanvas 材质上。
 */

/** 单个材质的外观声明。 */
export interface ModelMaterialInfo {
  /** 漫反射贴图 URL。 */
  baseColor?: string;
  /** 镂空透明贴图 URL（植物叶片等）。 */
  opacity?: string;
  /** 法线贴图 URL（表面起伏细节）。 */
  normal?: string;
  /** 按资产 RMA 贴图 URL：仅用 G 通道粗糙度（金属度通道与无环境反射场景不合，弃用）。 */
  rma?: string;
  /** 标量透明度（0-1，玻璃等半透明纯材质）。 */
  opacityValue?: number;
  /** 金属度标量（0-1，铬件等纯材质）。 */
  metallic?: number;
  /** 粗糙度标量（0-1，纯材质）。 */
  roughness?: number;
  /** 自发光颜色（0-1 线性 RGB，灯罩等纯材质）。 */
  emissive?: [number, number, number];
  /** 无贴图时的漫反射颜色（0-1 线性 RGB）。 */
  tint?: [number, number, number];
}

/** key：UE 材质资产名（匹配时忽略大小写与符号）。 */
export type ModelMaterialMap = Record<string, ModelMaterialInfo>;

export interface ModelLibraryEntry {
  id: string;
  name: string;
  category: string;
  fileName: string;
  fileUrl: string;
  unitScale: number;
  source: string;
  sizeKb: number;
  /** 材质回填映射：GLB 里只有 FBX 占位材质，无贴图。 */
  materials?: ModelMaterialMap;
}

export const MODEL_LIBRARY_CATEGORIES = ["家具","装饰","灯具","厨房","地面","植物","自然","背景"] as const;

const CINE57_SOURCE = "Cine57";

export const MODEL_LIBRARY: ModelLibraryEntry[] = [
  { id: "bed-12a", name: "双人床 A", category: "家具", fileName: "SM_Bed_12a.glb", fileUrl: "/models/cine57/SM_Bed_12a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 2429, materials: {"MI_Bed_12a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12a_ALB.TX_Bed_12a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12a_NRM.TX_Bed_12a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12a_RMA.TX_Bed_12a_RMA.jpg"},"MI_Bed_12b":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12b_ALB.TX_Bed_12b_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12b_NRM.TX_Bed_12b_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12b_RMA.TX_Bed_12b_RMA.jpg"},"MI_Bed_12c":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12c_ALB.TX_Bed_12c_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12c_NRM.TX_Bed_12c_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12c_RMA.TX_Bed_12c_RMA.jpg"}} },
  { id: "bed-19a", name: "单人床", category: "家具", fileName: "SM_Bed_19a.glb", fileUrl: "/models/cine57/SM_Bed_19a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 1714, materials: {"MI_Bed_19b":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19b_ALB.TX_Bed_19b_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19b_NRM.TX_Bed_19b_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19b_RMA.TX_Bed_19b_RMA.jpg"},"MI_Bed_19a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19a_ALB.TX_Bed_19a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19a_NRM.TX_Bed_19a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19a_RMA.TX_Bed_19a_RMA.jpg"},"MI_Bed_19c":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19c_ALB.TX_Bed_19c_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19c_NRM.TX_Bed_19c_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19c_RMA.TX_Bed_19c_RMA.jpg"}} },
  { id: "bed-frame-01a", name: "床架", category: "家具", fileName: "SM_Bed_Frame_01a.glb", fileUrl: "/models/cine57/SM_Bed_Frame_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 1491, materials: {"MI_Bed_Frame_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_Frame_01a_ALB.TX_Bed_Frame_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_Frame_01a_NRM.TX_Bed_Frame_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_Frame_01a_RMA.TX_Bed_Frame_01a_RMA.jpg"}} },
  { id: "sofa-pullout-01a", name: "沙发床", category: "家具", fileName: "SM_Sofa_Pullout_01a.glb", fileUrl: "/models/cine57/SM_Sofa_Pullout_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 161, materials: {"MI_Sofa_Pullout_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Sofa_Pullout_01a_ALB.TX_Sofa_Pullout_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Sofa_Pullout_01a_NRM.TX_Sofa_Pullout_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Sofa_Pullout_01a_RMA.TX_Sofa_Pullout_01a_RMA.jpg"}} },
  { id: "crib-baby-01a", name: "婴儿床", category: "家具", fileName: "SM_Crib_Baby_01a.glb", fileUrl: "/models/cine57/SM_Crib_Baby_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 386, materials: {"MI_Crib_Baby_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Crib_Baby_01a_ALB.TX_Crib_Baby_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Crib_Baby_01a_NRM.TX_Crib_Baby_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Crib_Baby_01a_RMA.TX_Crib_Baby_01a_RMA.jpg"}} },
  { id: "pillow-bed-01a", name: "床头枕", category: "装饰", fileName: "SM_Pillow_Bed_01a.glb", fileUrl: "/models/cine57/SM_Pillow_Bed_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 175, materials: {"MI_Pillows_Bed_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Pillows_Bed_01a_ALB.TX_Pillows_Bed_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Pillows_Bed_01a_NRM.TX_Pillows_Bed_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Pillows_Bed_01a_RMA.TX_Pillows_Bed_01a_RMA.jpg"}} },
  { id: "desk-office-08a", name: "办公桌 A", category: "家具", fileName: "SM_Desk_Office_08a.glb", fileUrl: "/models/cine57/SM_Desk_Office_08a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 214, materials: {"MI_Desk_Office_08a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Office_08a_ALB.TX_Desk_Office_08a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Office_08a_NRM.TX_Desk_Office_08a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Office_08a_RMA.TX_Desk_Office_08a_RMA.jpg"}} },
  { id: "desk-03a", name: "书桌", category: "家具", fileName: "SM_Desk_03a.glb", fileUrl: "/models/cine57/SM_Desk_03a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 88, materials: {"MI_Desk_03a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_03a_ALB.TX_Desk_03a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_03a_NRM.TX_Desk_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_03a_RMA.TX_Desk_03a_RMA.jpg"}} },
  { id: "chair-desk-01a", name: "书桌椅", category: "家具", fileName: "SM_Chair_Desk_01a.glb", fileUrl: "/models/cine57/SM_Chair_Desk_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 534, materials: {"MI_Chair_Desk_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Desk_01_ALB.TX_Chair_Desk_01_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Desk_01_NRM.TX_Chair_Desk_01_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Desk_01_RMA.TX_Chair_Desk_01_RMA.jpg"}} },
  { id: "chair-set-05a", name: "椅子 A", category: "家具", fileName: "SM_Chair_Set_05a.glb", fileUrl: "/models/cine57/SM_Chair_Set_05a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 549, materials: {"MI_Chair_Set_05a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_05a_ALB.TX_Chair_Set_05a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_05a_NRM.TX_Chair_Set_05a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_05a_RMA.TX_Chair_Set_05a_RMA.jpg"}} },
  { id: "chair-set-09a", name: "椅子 B", category: "家具", fileName: "SM_Chair_Set_09a.glb", fileUrl: "/models/cine57/SM_Chair_Set_09a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 563, materials: {"MI_Chair_Set_09a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_09a_ALB.TX_Chair_Set_09a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_09a_NRM.TX_Chair_Set_09a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_09a_RMA.TX_Chair_Set_09a_RMA.jpg"}} },
  { id: "table", name: "餐桌", category: "家具", fileName: "SM_Table.glb", fileUrl: "/models/cine57/SM_Table.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 343, materials: {"M_Chair":{"roughness":0.25,"tint":[0.0721,0.0721,0.0721]},"M_Table_Top":{"roughness":0.25,"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Marble_A.T_Marble_A.jpg"}} },
  { id: "coffee-table", name: "茶几", category: "家具", fileName: "SM_Coffee_table.glb", fileUrl: "/models/cine57/SM_Coffee_table.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 170, materials: {"M_Coffee_table":{"roughness":0.25,"tint":[0.8,0.8,0.8]},"M_Coffee_table_bottom":{"roughness":0.30000001192092896,"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Wood_5_a.T_Wood_5_a.jpg"},"M_Coffee_table_2":{"roughness":0.25,"tint":[0.2257,0.2257,0.2257]}} },
  { id: "book-set-01a", name: "书堆 A", category: "装饰", fileName: "SM_Book_Set_01a.glb", fileUrl: "/models/cine57/SM_Book_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 185, materials: {"MI_Bookset_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_ALB.TX_Bookset_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_NRM.TX_Bookset_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_RMA.TX_Bookset_01a_RMA.jpg"}} },
  { id: "book-set-05a", name: "书堆 B", category: "装饰", fileName: "SM_Book_Set_05a.glb", fileUrl: "/models/cine57/SM_Book_Set_05a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 37, materials: {"MI_Bookset_05a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Book_Set_05a_ALB.TX_Book_Set_05a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Book_Set_05a_NRM.TX_Book_Set_05a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Book_Set_05a_RMA.TX_Book_Set_05a_RMA.jpg"}} },
  { id: "candle-set-02a", name: "烛台组", category: "装饰", fileName: "SM_Candle_Set_02a.glb", fileUrl: "/models/cine57/SM_Candle_Set_02a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 133, materials: {"MI_Candle_Set_02a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Candle_Set_02a_ALB.TX_Candle_Set_02a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Candle_Set_02a_NRM.TX_Candle_Set_02a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Candle_Set_02a_RMA.TX_Candle_Set_02a_RMA.jpg"}} },
  { id: "house-decor-11a", name: "家居摆件", category: "装饰", fileName: "SM_House_Decor_11a.glb", fileUrl: "/models/cine57/SM_House_Decor_11a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 70, materials: {"MI_House_Decor_11a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_House_Decor_11a_ALB.TX_House_Decor_11a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_House_Decor_11a_NRM.TX_House_Decor_11a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_House_Decor_11a_RMA.TX_House_Decor_11a_RMA.jpg"}} },
  { id: "pillow-set-06a", name: "抱枕组", category: "装饰", fileName: "SM_Pillow_Set_06a.glb", fileUrl: "/models/cine57/SM_Pillow_Set_06a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 52, materials: {"MI_Pillow_Set_06a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Pillow_Set_06a_ALB.TX_Pillow_Set_06a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Pillow_Set_06a_NRM.TX_Pillow_Set_06a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Pillow_Set_06a_RMA.TX_Pillow_Set_06a_RMA.jpg"}} },
  { id: "chinese-vases-01a", name: "瓷瓶 A", category: "装饰", fileName: "SM_Chinese_Vases_01a.glb", fileUrl: "/models/cine57/SM_Chinese_Vases_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 327, materials: {"MI_Chinese_Vases_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_ALB.TX_Chinese_Vases_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_NRM.TX_Chinese_Vases_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_RMA.TX_Chinese_Vases_01a_RMA.jpg"}} },
  { id: "chinese-vases-01b", name: "瓷瓶 B", category: "装饰", fileName: "SM_Chinese_Vases_01b.glb", fileUrl: "/models/cine57/SM_Chinese_Vases_01b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 561, materials: {"MI_Chinese_Vases_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_ALB.TX_Chinese_Vases_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_NRM.TX_Chinese_Vases_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_RMA.TX_Chinese_Vases_01a_RMA.jpg"}} },
  { id: "knick-knacks-31a", name: "小摆件", category: "装饰", fileName: "SM_Knick_Knacks_31a.glb", fileUrl: "/models/cine57/SM_Knick_Knacks_31a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 687, materials: {"MI_Knick_Knacks_31a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knacks_31a_ALB.TX_Knick_Knacks_31a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knacks_31a_NRM.TX_Knick_Knacks_31a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knacks_31a_RMA.TX_Knick_Knacks_31a_RMA.jpg"}} },
  { id: "chinese-lamp-01a", name: "宫灯", category: "灯具", fileName: "SM_Chinese_Lamp_01a.glb", fileUrl: "/models/cine57/SM_Chinese_Lamp_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 174, materials: {"MI_Chinese_Lamp_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Lamp_01a_ALB.TX_Chinese_Lamp_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Lamp_01a_NRM.TX_Chinese_Lamp_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Lamp_01a_RMA.TX_Chinese_Lamp_01a_RMA.jpg"}} },
  { id: "plant-0", name: "盆栽 A", category: "植物", fileName: "SM_plant_0.glb", fileUrl: "/models/cine57/SM_plant_0.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 931, materials: {"M_leaf_19":{"baseColor":"/models/cine57/tex/_EnvHouse_HQ_Interior_plants_Textures_T_PLANT_Aspadistra_2.T_PLANT_Aspadistra_2_baseColor.jpg"}} },
  { id: "plant-12", name: "盆栽 B", category: "植物", fileName: "SM_plant_12.glb", fileUrl: "/models/cine57/SM_plant_12.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 252, materials: {"M_leaf_18":{"baseColor":"/models/cine57/tex/_EnvHouse_HQ_Interior_plants_Textures_T_p80_2.T_p80_2_baseColor.jpg"}} },
  { id: "palm-tree-house-01a", name: "室内棕榈", category: "植物", fileName: "SM_Palm_Tree_House_01a.glb", fileUrl: "/models/cine57/SM_Palm_Tree_House_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 447, materials: {"MI_Palm_Tree_House_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Palm_Tree_House_01a_ALB.TX_Palm_Tree_House_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Palm_Tree_House_01a_NRM.TX_Palm_Tree_House_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Palm_Tree_House_01a_RMA.TX_Palm_Tree_House_01a_RMA.jpg"}} },
  { id: "big-rock-01", name: "巨石", category: "自然", fileName: "SM_Big_rock_01.glb", fileUrl: "/models/cine57/SM_Big_rock_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 449, materials: {"MI_Big_rock_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Big_rock_01_BC.T_Big_rock_01_BC_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Big_rock_01_N.T_Big_rock_01_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Big_rock_01_N.T_Big_rock_01_N.jpg"}} },
  { id: "flat-rock-01", name: "扁石", category: "自然", fileName: "SM_flat_rock_01.glb", fileUrl: "/models/cine57/SM_flat_rock_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 238, materials: {"MI_Flat_rock_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_BC_H.T_Flat_rock_01_tiled_BC_H_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_N.T_Flat_rock_01_tiled_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_N.T_Flat_rock_01_tiled_N.jpg"}} },
  { id: "ground-rock-01", name: "碎石 A", category: "自然", fileName: "SM_ground_rock_01.glb", fileUrl: "/models/cine57/SM_ground_rock_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 278, materials: {"MI_rocks_atlas_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_BC.T_rocks_atlas_01_BC_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N.jpg"}} },
  { id: "ground-rock-02", name: "碎石 B", category: "自然", fileName: "SM_ground_rock_02.glb", fileUrl: "/models/cine57/SM_ground_rock_02.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 145, materials: {"MI_rocks_atlas_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_BC.T_rocks_atlas_01_BC_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N.jpg"}} },
  { id: "food-shipment-01a", name: "食材组合 A", category: "厨房", fileName: "SM_FoodShipmentSet_01a.glb", fileUrl: "/models/cine57/SM_FoodShipmentSet_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 181, materials: {"MI_FoodShipment_01a":{"baseColor":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_ALB.TX_FoodShipment_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_NRM.TX_FoodShipment_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_RMA.TX_FoodShipment_01a_RMA.jpg"}} },
  { id: "food-shipment-01b", name: "食材组合 B", category: "厨房", fileName: "SM_FoodShipmentSet_01b.glb", fileUrl: "/models/cine57/SM_FoodShipmentSet_01b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 176, materials: {"MI_FoodShipment_01a":{"baseColor":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_ALB.TX_FoodShipment_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_NRM.TX_FoodShipment_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_RMA.TX_FoodShipment_01a_RMA.jpg"}} },
  { id: "food-shipment-01c", name: "食材组合 C", category: "厨房", fileName: "SM_FoodShipmentSet_01c.glb", fileUrl: "/models/cine57/SM_FoodShipmentSet_01c.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 244, materials: {"MI_FoodShipment_01a":{"baseColor":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_ALB.TX_FoodShipment_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_NRM.TX_FoodShipment_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_RMA.TX_FoodShipment_01a_RMA.jpg"}} },
  { id: "food-shipment-01d", name: "食材组合 D", category: "厨房", fileName: "SM_FoodShipmentSet_01d.glb", fileUrl: "/models/cine57/SM_FoodShipmentSet_01d.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 224, materials: {"MI_FoodShipment_01a":{"baseColor":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_ALB.TX_FoodShipment_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_NRM.TX_FoodShipment_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_RMA.TX_FoodShipment_01a_RMA.jpg"}} },
  { id: "food-shipment-01e", name: "食材组合 E", category: "厨房", fileName: "SM_FoodShipmentSet_01e.glb", fileUrl: "/models/cine57/SM_FoodShipmentSet_01e.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 162, materials: {"MI_FoodShipment_01a":{"baseColor":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_ALB.TX_FoodShipment_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_NRM.TX_FoodShipment_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_RMA.TX_FoodShipment_01a_RMA.jpg"}} },
  { id: "rugs-03a", name: "地毯 03A", category: "地面", fileName: "SM_Rugs_03a.glb", fileUrl: "/models/cine57/SM_Rugs_03a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 59, materials: {"MI_Rug_03a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_ALB.TX_Rugs_03a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_NRM.TX_Rugs_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_RMA.TX_Rugs_03a_RMA.jpg"}} },
  { id: "rugs-03b", name: "地毯 03B", category: "地面", fileName: "SM_Rugs_03b.glb", fileUrl: "/models/cine57/SM_Rugs_03b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 79, materials: {"MI_Rug_03b":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03b_ALB.TX_Rugs_03b_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_NRM.TX_Rugs_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_RMA.TX_Rugs_03a_RMA.jpg"}} },
  { id: "rugs-03c", name: "地毯 03C", category: "地面", fileName: "SM_Rugs_03c.glb", fileUrl: "/models/cine57/SM_Rugs_03c.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 81, materials: {"MI_Rug_03c":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03c_ALB.TX_Rugs_03c_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_NRM.TX_Rugs_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_RMA.TX_Rugs_03a_RMA.jpg"}} },
  { id: "rug-04a", name: "花纹地毯", category: "地面", fileName: "SM_Rug_04a.glb", fileUrl: "/models/cine57/SM_Rug_04a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 42, materials: {"MI_Rug_04a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rug_NN_04a_ALB.TX_Rug_NN_04a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rug_NN_04a_NRM.TX_Rug_NN_04a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rug_NN_04a_RMA.TX_Rug_NN_04a_RMA.jpg"}} },
  { id: "brick-stove-1", name: "砖砌炉灶 · 组合", category: "厨房", fileName: "SM_brick_stove_1.glb", fileUrl: "/models/cine57/SM_brick_stove_1.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 242, materials: {"MI_brick_stove_1":{"baseColor":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_T_grey.T_grey_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_house_modular_elements_T_brick_stove_1_Normal.T_brick_stove_1_Normal_normal.jpg","rma":"/models/cine57/tex/s_house_modular_elements_T_brick_stove_1_OcclusionRoughnessMetallic.T_brick_stove_1_OcclusionRoughnessMetallic.jpg"}} },
  { id: "brick-stove-2", name: "砖砌炉灶 · 主体", category: "厨房", fileName: "SM_brick_stove_2.glb", fileUrl: "/models/cine57/SM_brick_stove_2.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 23, materials: {"MI_brick_stove_2":{"baseColor":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_T_grey.T_grey_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_house_modular_elements_T_brick_stove_1_Normal.T_brick_stove_1_Normal_normal.jpg","rma":"/models/cine57/tex/s_house_modular_elements_T_brick_stove_1_OcclusionRoughnessMetallic.T_brick_stove_1_OcclusionRoughnessMetallic.jpg"}} },
  { id: "brick-stove-3", name: "砖砌炉灶 · 部件", category: "厨房", fileName: "SM_brick_stove_3.glb", fileUrl: "/models/cine57/SM_brick_stove_3.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 23, materials: {"MI_brick_stove_2":{"baseColor":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_T_grey.T_grey_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_house_modular_elements_T_brick_stove_1_Normal.T_brick_stove_1_Normal_normal.jpg","rma":"/models/cine57/tex/s_house_modular_elements_T_brick_stove_1_OcclusionRoughnessMetallic.T_brick_stove_1_OcclusionRoughnessMetallic.jpg"}} },
  { id: "decorative-1", name: "装饰构件 1", category: "装饰", fileName: "SM_decorative_elements_1.glb", fileUrl: "/models/cine57/SM_decorative_elements_1.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 19, materials: {"MI_decorative_elements_1":{"baseColor":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_T_grey.T_grey_baseColor.jpg","normal":"/models/cine57/tex/_Abandoned_house_Textures_house_modular_elements_T_decorative_elements_1_Normal.T_decorative_elements_1_Normal_normal.jpg","rma":"/models/cine57/tex/elements_T_decorative_elements_1_OcclusionRoughnessMetallic.T_decorative_elements_1_OcclusionRoughnessMetallic.jpg"}} },
  { id: "decorative-2", name: "装饰构件 2", category: "装饰", fileName: "SM_decorative_elements_2.glb", fileUrl: "/models/cine57/SM_decorative_elements_2.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 23, materials: {"MI_decorative_elements_1":{"baseColor":"/models/cine57/tex/_EnvHouse_Abandoned_house_Textures_T_grey.T_grey_baseColor.jpg","normal":"/models/cine57/tex/_Abandoned_house_Textures_house_modular_elements_T_decorative_elements_1_Normal.T_decorative_elements_1_Normal_normal.jpg","rma":"/models/cine57/tex/elements_T_decorative_elements_1_OcclusionRoughnessMetallic.T_decorative_elements_1_OcclusionRoughnessMetallic.jpg"}} },
  { id: "z-backdrop-01a", name: "纯色背景板", category: "背景", fileName: "SM_ZBackdrop_01a.glb", fileUrl: "/models/cine57/SM_ZBackdrop_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 4, materials: {"MI_Template_BaseGray_03":{"tint":[0.302,0.302,0.31]}} },
];

export function getModelLibraryEntry(id: string | undefined): ModelLibraryEntry | null {
  if (!id) return null;
  return MODEL_LIBRARY.find((entry) => entry.id === id) ?? null;
}
