/**
 * 模型库目录：内置常用模型的静态清单。
 *
 * 模型文件放在 client/public/models/ 下由前端静态服务；目录只是数据，
 * 不做任何运行时探测。数据来自 Cine57（UE 5.7）经 FBX + FBX2glTF 的
 * 导出管线（见 docs/wiki/product/model-library.md），几何单位已是米。
 * materials 把 FBX 带出的材质资源名映射到真实贴图，运行时由
 * modelLibrary3d/modelMaterials.ts 回填到 PlayCanvas 材质上。
 */

import { attachModelUsageInstructions, type ModelUsageInstruction } from "./modelLibraryUsage.ts";

/** 单个材质的外观声明。 */
export interface ModelMaterialInfo {
  /** 漫反射贴图 URL。 */
  baseColor?: string;
  /** 镂空透明贴图 URL（植物叶片等）。 */
  opacity?: string;
  /** 法线贴图 URL（表面起伏细节）。 */
  normal?: string;
  /** 按资产 RMA 贴图 URL：仅用 G 通道粗糙度（金属度通道与无环境反射场景不合，弃用）。 */
  rma?: string;
  /** 标量透明度（0-1，玻璃等半透明纯材质）。 */
  opacityValue?: number;
  /** 金属度标量（0-1，铬件等纯材质）。 */
  metallic?: number;
  /** 粗糙度标量（0-1，纯材质）。 */
  roughness?: number;
  /** 自发光颜色（0-1 线性 RGB，灯罩等纯材质）。 */
  emissive?: [number, number, number];
  /** 无贴图时的漫反射颜色（0-1 线性 RGB）。 */
  tint?: [number, number, number];
}

/** key：UE 材质资产名（匹配时忽略大小写与符号）。 */
export type ModelMaterialMap = Record<string, ModelMaterialInfo>;

/** 模型库 3D 预览的专用外观实验标识。 */
export type ModelPreviewAppearance = "character-texture-test";

export interface ModelLibraryEntry {
  id: string;
  name: string;
  category: string;
  fileName: string;
  fileUrl: string;
  unitScale: number;
  source: string;
  sizeKb: number;
  /** 模型在分镜中的支撑面、安装方式和朝向说明。 */
  usage: ModelUsageInstruction;
  /** 材质回填映射：GLB 里只有 FBX 占位材质，无贴图。 */
  materials?: ModelMaterialMap;
  /** 可选的模型库专用预览外观。未声明时沿用普通材质回填。 */
  previewAppearance?: ModelPreviewAppearance;
}

export const MODEL_LIBRARY_CATEGORIES = ["家具","容器与箱子","厨房与餐具","日用小物","书籍与办公","玩具/装饰品","灯具","地面","盆栽","石头","灌木","树木","草","花","户外","卫浴","角色"] as const;

const CINE57_SOURCE = "Cine57";

const MODEL_LIBRARY_BASE: Omit<ModelLibraryEntry, "usage">[] = [
  { id: "bed-12a", name: "双人床 A", category: "家具", fileName: "SM_Bed_12a.glb", fileUrl: "/models/cine57/SM_Bed_12a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 2429, materials: {"MI_Bed_12a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12a_ALB.TX_Bed_12a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12a_NRM.TX_Bed_12a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12a_RMA.TX_Bed_12a_RMA.jpg"},"MI_Bed_12b":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12b_ALB.TX_Bed_12b_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12b_NRM.TX_Bed_12b_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12b_RMA.TX_Bed_12b_RMA.jpg"},"MI_Bed_12c":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12c_ALB.TX_Bed_12c_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12c_NRM.TX_Bed_12c_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_12c_RMA.TX_Bed_12c_RMA.jpg"}} },
  { id: "bed-19a", name: "单人床", category: "家具", fileName: "SM_Bed_19a.glb", fileUrl: "/models/cine57/SM_Bed_19a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 1714, materials: {"MI_Bed_19b":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19b_ALB.TX_Bed_19b_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19b_NRM.TX_Bed_19b_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19b_RMA.TX_Bed_19b_RMA.jpg"},"MI_Bed_19a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19a_ALB.TX_Bed_19a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19a_NRM.TX_Bed_19a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19a_RMA.TX_Bed_19a_RMA.jpg"},"MI_Bed_19c":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19c_ALB.TX_Bed_19c_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19c_NRM.TX_Bed_19c_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_19c_RMA.TX_Bed_19c_RMA.jpg"}} },
  { id: "bed-frame-01a", name: "床架", category: "家具", fileName: "SM_Bed_Frame_01a.glb", fileUrl: "/models/cine57/SM_Bed_Frame_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 1491, materials: {"MI_Bed_Frame_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_Frame_01a_ALB.TX_Bed_Frame_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_Frame_01a_NRM.TX_Bed_Frame_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Bed_Frame_01a_RMA.TX_Bed_Frame_01a_RMA.jpg"}} },
  { id: "sofa-pullout-01a", name: "沙发床", category: "家具", fileName: "SM_Sofa_Pullout_01a.glb", fileUrl: "/models/cine57/SM_Sofa_Pullout_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 161, materials: {"MI_Sofa_Pullout_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Sofa_Pullout_01a_ALB.TX_Sofa_Pullout_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Sofa_Pullout_01a_NRM.TX_Sofa_Pullout_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Sofa_Pullout_01a_RMA.TX_Sofa_Pullout_01a_RMA.jpg"}} },
  { id: "crib-baby-01a", name: "婴儿床", category: "家具", fileName: "SM_Crib_Baby_01a.glb", fileUrl: "/models/cine57/SM_Crib_Baby_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 386, materials: {"MI_Crib_Baby_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Crib_Baby_01a_ALB.TX_Crib_Baby_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Crib_Baby_01a_NRM.TX_Crib_Baby_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Crib_Baby_01a_RMA.TX_Crib_Baby_01a_RMA.jpg"}} },
  { id: "pillow-bed-01a", name: "床头枕", category: "玩具/装饰品", fileName: "SM_Pillow_Bed_01a.glb", fileUrl: "/models/cine57/SM_Pillow_Bed_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 175, materials: {"MI_Pillows_Bed_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Pillows_Bed_01a_ALB.TX_Pillows_Bed_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Pillows_Bed_01a_NRM.TX_Pillows_Bed_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL16_Bedroom_Textures_TX_Pillows_Bed_01a_RMA.TX_Pillows_Bed_01a_RMA.jpg"}} },
  { id: "desk-office-08a", name: "办公桌 A", category: "家具", fileName: "SM_Desk_Office_08a.glb", fileUrl: "/models/cine57/SM_Desk_Office_08a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 214, materials: {"MI_Desk_Office_08a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Office_08a_ALB.TX_Desk_Office_08a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Office_08a_NRM.TX_Desk_Office_08a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Office_08a_RMA.TX_Desk_Office_08a_RMA.jpg"}} },
  { id: "desk-03a", name: "书桌", category: "家具", fileName: "SM_Desk_03a.glb", fileUrl: "/models/cine57/SM_Desk_03a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 88, materials: {"MI_Desk_03a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_03a_ALB.TX_Desk_03a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_03a_NRM.TX_Desk_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_03a_RMA.TX_Desk_03a_RMA.jpg"}} },
  { id: "chair-desk-01a", name: "书桌椅", category: "家具", fileName: "SM_Chair_Desk_01a.glb", fileUrl: "/models/cine57/SM_Chair_Desk_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 534, materials: {"MI_Chair_Desk_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Desk_01_ALB.TX_Chair_Desk_01_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Desk_01_NRM.TX_Chair_Desk_01_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Desk_01_RMA.TX_Chair_Desk_01_RMA.jpg"}} },
  { id: "chair-set-05a", name: "椅子 A", category: "家具", fileName: "SM_Chair_Set_05a.glb", fileUrl: "/models/cine57/SM_Chair_Set_05a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 549, materials: {"MI_Chair_Set_05a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_05a_ALB.TX_Chair_Set_05a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_05a_NRM.TX_Chair_Set_05a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_05a_RMA.TX_Chair_Set_05a_RMA.jpg"}} },
  { id: "chair-set-09a", name: "椅子 B", category: "家具", fileName: "SM_Chair_Set_09a.glb", fileUrl: "/models/cine57/SM_Chair_Set_09a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 563, materials: {"MI_Chair_Set_09a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_09a_ALB.TX_Chair_Set_09a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_09a_NRM.TX_Chair_Set_09a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Chair_Set_09a_RMA.TX_Chair_Set_09a_RMA.jpg"}} },
  { id: "table", name: "餐桌", category: "家具", fileName: "SM_Table.glb", fileUrl: "/models/cine57/SM_Table.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 343, materials: {"M_Chair":{"roughness":0.25,"tint":[0.0721,0.0721,0.0721]},"M_Table_Top":{"roughness":0.25,"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Marble_A.T_Marble_A.jpg"}} },
  { id: "coffee-table", name: "茶几", category: "家具", fileName: "SM_Coffee_table.glb", fileUrl: "/models/cine57/SM_Coffee_table.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 169, materials: {"M_Coffee_table":{"roughness":0.25,"tint":[0.8,0.8,0.8]},"M_Coffee_table_bottom":{"roughness":0.30000001192092896,"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Wood_5_a.T_Wood_5_a.jpg"},"M_Coffee_table_2":{"roughness":0.25,"tint":[0.2257,0.2257,0.2257]}} },
  { id: "book-set-01a", name: "书堆 A", category: "书籍与办公", fileName: "SM_Book_Set_01a.glb", fileUrl: "/models/cine57/SM_Book_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 185, materials: {"MI_Bookset_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_ALB.TX_Bookset_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_NRM.TX_Bookset_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_RMA.TX_Bookset_01a_RMA.jpg"}} },
  { id: "book-set-05a", name: "书堆 B", category: "书籍与办公", fileName: "SM_Book_Set_05a.glb", fileUrl: "/models/cine57/SM_Book_Set_05a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 37, materials: {"MI_Bookset_05a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Book_Set_05a_ALB.TX_Book_Set_05a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Book_Set_05a_NRM.TX_Book_Set_05a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Book_Set_05a_RMA.TX_Book_Set_05a_RMA.jpg"}} },
  { id: "candle-set-02a", name: "烛台组", category: "玩具/装饰品", fileName: "SM_Candle_Set_02a.glb", fileUrl: "/models/cine57/SM_Candle_Set_02a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 133, materials: {"MI_Candle_Set_02a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Candle_Set_02a_ALB.TX_Candle_Set_02a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Candle_Set_02a_NRM.TX_Candle_Set_02a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Candle_Set_02a_RMA.TX_Candle_Set_02a_RMA.jpg"}} },
  { id: "house-decor-11a", name: "家居摆件", category: "玩具/装饰品", fileName: "SM_House_Decor_11a.glb", fileUrl: "/models/cine57/SM_House_Decor_11a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 70, materials: {"MI_House_Decor_11a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_House_Decor_11a_ALB.TX_House_Decor_11a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_House_Decor_11a_NRM.TX_House_Decor_11a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_House_Decor_11a_RMA.TX_House_Decor_11a_RMA.jpg"}} },
  { id: "pillow-set-06a", name: "抱枕组", category: "玩具/装饰品", fileName: "SM_Pillow_Set_06a.glb", fileUrl: "/models/cine57/SM_Pillow_Set_06a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 52, materials: {"MI_Pillow_Set_06a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Pillow_Set_06a_ALB.TX_Pillow_Set_06a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Pillow_Set_06a_NRM.TX_Pillow_Set_06a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Pillow_Set_06a_RMA.TX_Pillow_Set_06a_RMA.jpg"}} },
  { id: "chinese-vases-01a", name: "瓷瓶 A", category: "玩具/装饰品", fileName: "SM_Chinese_Vases_01a.glb", fileUrl: "/models/cine57/SM_Chinese_Vases_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 327, materials: {"MI_Chinese_Vases_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_ALB.TX_Chinese_Vases_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_NRM.TX_Chinese_Vases_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_RMA.TX_Chinese_Vases_01a_RMA.jpg"}} },
  { id: "chinese-vases-01b", name: "瓷瓶 B", category: "玩具/装饰品", fileName: "SM_Chinese_Vases_01b.glb", fileUrl: "/models/cine57/SM_Chinese_Vases_01b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 561, materials: {"MI_Chinese_Vases_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_ALB.TX_Chinese_Vases_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_NRM.TX_Chinese_Vases_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Vases_01a_RMA.TX_Chinese_Vases_01a_RMA.jpg"}} },
  { id: "knick-knacks-31a", name: "小摆件", category: "玩具/装饰品", fileName: "SM_Knick_Knacks_31a.glb", fileUrl: "/models/cine57/SM_Knick_Knacks_31a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 687, materials: {"MI_Knick_Knacks_31a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knacks_31a_ALB.TX_Knick_Knacks_31a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knacks_31a_NRM.TX_Knick_Knacks_31a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knacks_31a_RMA.TX_Knick_Knacks_31a_RMA.jpg"}} },
  { id: "chinese-lamp-01a", name: "宫灯", category: "灯具", fileName: "SM_Chinese_Lamp_01a.glb", fileUrl: "/models/cine57/SM_Chinese_Lamp_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 174, materials: {"MI_Chinese_Lamp_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Lamp_01a_ALB.TX_Chinese_Lamp_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Lamp_01a_NRM.TX_Chinese_Lamp_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Chinese_Lamp_01a_RMA.TX_Chinese_Lamp_01a_RMA.jpg"}} },
  { id: "plant-0", name: "盆栽 A", category: "盆栽", fileName: "SM_plant_0.glb", fileUrl: "/models/cine57/SM_plant_0.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 931, materials: {"M_leaf_19":{"baseColor":"/models/cine57/tex/_EnvHouse_HQ_Interior_plants_Textures_T_PLANT_Aspadistra_2.T_PLANT_Aspadistra_2_baseColor.jpg"}} },
  { id: "plant-12", name: "盆栽 B", category: "盆栽", fileName: "SM_plant_12.glb", fileUrl: "/models/cine57/SM_plant_12.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 252, materials: {"M_leaf_18":{"baseColor":"/models/cine57/tex/_EnvHouse_HQ_Interior_plants_Textures_T_p80_2.T_p80_2_baseColor.jpg"}} },
  { id: "palm-tree-house-01a", name: "室内棕榈", category: "盆栽", fileName: "SM_Palm_Tree_House_01a.glb", fileUrl: "/models/cine57/SM_Palm_Tree_House_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 447, materials: {"MI_Palm_Tree_House_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Palm_Tree_House_01a_ALB.TX_Palm_Tree_House_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Palm_Tree_House_01a_NRM.TX_Palm_Tree_House_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Palm_Tree_House_01a_RMA.TX_Palm_Tree_House_01a_RMA.jpg"}} },
  { id: "ground-rock-01", name: "碎石 A", category: "石头", fileName: "SM_ground_rock_01.glb", fileUrl: "/models/cine57/SM_ground_rock_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 278, materials: {"MI_rocks_atlas_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_BC.T_rocks_atlas_01_BC_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N.jpg"}} },
  { id: "ground-rock-02", name: "碎石 B", category: "石头", fileName: "SM_ground_rock_02.glb", fileUrl: "/models/cine57/SM_ground_rock_02.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 145, materials: {"MI_rocks_atlas_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_BC.T_rocks_atlas_01_BC_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_atlas_01_N.T_rocks_atlas_01_N.jpg"}} },
  { id: "food-shipment-01a", name: "纸箱·食材组合", category: "容器与箱子", fileName: "SM_FoodShipmentSet_01a.glb", fileUrl: "/models/cine57/SM_FoodShipmentSet_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 181, materials: {"MI_FoodShipment_01a":{"baseColor":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_ALB.TX_FoodShipment_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_NRM.TX_FoodShipment_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_KitchenCombo_Kitchen_VOL2_Textures_Unique_TX_FoodShipment_01a_RMA.TX_FoodShipment_01a_RMA.jpg"}} },
  { id: "rugs-03a", name: "地毯 03A", category: "地面", fileName: "SM_Rugs_03a.glb", fileUrl: "/models/cine57/SM_Rugs_03a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 59, materials: {"MI_Rug_03a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_ALB.TX_Rugs_03a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_NRM.TX_Rugs_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_RMA.TX_Rugs_03a_RMA.jpg"}} },
  { id: "rugs-03b", name: "地毯 03B", category: "地面", fileName: "SM_Rugs_03b.glb", fileUrl: "/models/cine57/SM_Rugs_03b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 79, materials: {"MI_Rug_03b":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03b_ALB.TX_Rugs_03b_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_NRM.TX_Rugs_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_RMA.TX_Rugs_03a_RMA.jpg"}} },
  { id: "rugs-03c", name: "地毯 03C", category: "地面", fileName: "SM_Rugs_03c.glb", fileUrl: "/models/cine57/SM_Rugs_03c.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 81, materials: {"MI_Rug_03c":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03c_ALB.TX_Rugs_03c_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_NRM.TX_Rugs_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rugs_03a_RMA.TX_Rugs_03a_RMA.jpg"}} },
  { id: "rug-04a", name: "花纹地毯", category: "地面", fileName: "SM_Rug_04a.glb", fileUrl: "/models/cine57/SM_Rug_04a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 42, materials: {"MI_Rug_04a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rug_NN_04a_ALB.TX_Rug_NN_04a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rug_NN_04a_NRM.TX_Rug_NN_04a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL11_Rugs_Textures_TX_Rug_NN_04a_RMA.TX_Rug_NN_04a_RMA.jpg"}} },
  { id: "burger-food-set-01a", name: "汉堡餐", category: "厨房与餐具", fileName: "SM_Burger_Food_Set_01a.glb", fileUrl: "/models/cine57/SM_Burger_Food_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 407, materials: {"MI_Burger_Food_Set_01a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Burger_Food_Set_01a_ALB.TX_Burger_Food_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Burger_Food_Set_01a_NRM.TX_Burger_Food_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Burger_Food_Set_01a_RMA.TX_Burger_Food_Set_01a_RMA.jpg"}} },
  { id: "chair-table-set-11a", name: "餐桌椅组", category: "家具", fileName: "SM_Chair_Table_Set_11a.glb", fileUrl: "/models/cine57/SM_Chair_Table_Set_11a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 344, materials: {"MI_Chair_Table_Set_11a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Chair_Table_Set_11a_ALB.TX_Chair_Table_Set_11a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Chair_Table_Set_11a_NRM.TX_Chair_Table_Set_11a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Chair_Table_Set_11a_RMA.TX_Chair_Table_Set_11a_RMA.jpg"}} },
  { id: "chinese-food-01a", name: "中式餐食", category: "厨房与餐具", fileName: "SM_Chinese_Food_01a.glb", fileUrl: "/models/cine57/SM_Chinese_Food_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 270, materials: {"MI_Chinese_Food_01a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Chinese_Food_01a_ALB.TX_Chinese_Food_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Chinese_Food_01a_NRM.TX_Chinese_Food_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Chinese_Food_01a_RMA.TX_Chinese_Food_01a_RMA.jpg"}} },
  { id: "coffee-machine-01a", name: "咖啡机", category: "厨房与餐具", fileName: "SM_Coffee_Machine_01a.glb", fileUrl: "/models/cine57/SM_Coffee_Machine_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 710, materials: {"MI_Coffee_Machine_01a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Coffee_Machine_01a_ALB.TX_Coffee_Machine_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Coffee_Machine_01a_NRM.TX_Coffee_Machine_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Coffee_Machine_01a_RMA.TX_Coffee_Machine_01a_RMA.jpg"}} },
  { id: "cooking-tools-01a", name: "烹饪工具", category: "厨房与餐具", fileName: "SM_Cooking_Tools_01a.glb", fileUrl: "/models/cine57/SM_Cooking_Tools_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 50, materials: {"MI_Cooking_Tools_01a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL1_Textures_TX_Cooking_Tools_01a_ALB.TX_Cooking_Tools_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL1_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL1_Textures_TX_Cooking_Tools_01a_NRM.TX_Cooking_Tools_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL1_Textures_TX_Cooking_Tools_01a_RMA.TX_Cooking_Tools_01a_RMA.jpg"}} },
  { id: "dining-table-set-01a", name: "餐桌椅组 B", category: "家具", fileName: "SM_Dining_Table_Set_01a.glb", fileUrl: "/models/cine57/SM_Dining_Table_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 409, materials: {"MI_Dining_Table_Set_01a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Dining_Table_Set_01a_ALB.TX_Dining_Table_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Dining_Table_Set_01a_NRM.TX_Dining_Table_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Dining_Table_Set_01a_RMA.TX_Dining_Table_Set_01a_RMA.jpg"}} },
  { id: "dinner-desert-set-01a", name: "餐具甜品组", category: "厨房与餐具", fileName: "SM_Dinner_Desert_Set_01a.glb", fileUrl: "/models/cine57/SM_Dinner_Desert_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 596, materials: {"MI_Dinner_Desert_Set_01a":{"baseColor":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Dinner_Desert_Set_01a_ALB.TX_Dinner_Desert_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Dinner_Desert_Set_01a_NRM.TX_Dinner_Desert_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvCity_Restaurant_VOL3_Textures_TX_Dinner_Desert_Set_01a_RMA.TX_Dinner_Desert_Set_01a_RMA.jpg"}} },
  { id: "armchair", name: "扶手椅", category: "家具", fileName: "SM_Armchair.glb", fileUrl: "/models/cine57/SM_Armchair.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 655, materials: {"M_Armchair_Wood":{"roughness":0.4000000059604645,"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Wood_5_a.T_Wood_5_a.jpg"},"M_Armchair_seat":{"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Fabric_1_A.T_Fabric_1_A.jpg"},"M_Pillow":{"baseColor":"/models/cine57/tex/_EnvHouse_ArchVizInteriorVol2_Textures_T_Fabric_3_A.T_Fabric_3_A.jpg"}} },
  { id: "barrel-01", name: "木桶", category: "容器与箱子", fileName: "SM_Barrel_01.glb", fileUrl: "/models/cine57/SM_Barrel_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 94, materials: {"MI_Barrel_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_DiveBar_VOL2_Textures_Unique_TX_Barrel_01_ALB.TX_Barrel_01_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_DiveBar_VOL2_Textures_Unique_TX_Barrel_01_NRM.TX_Barrel_01_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_DiveBar_VOL2_Textures_Unique_TX_Barrel_01_RMA.TX_Barrel_01_RMA.jpg"}} },
  { id: "barstool-01a", name: "吧台凳", category: "家具", fileName: "SM_Barstool_01a.glb", fileUrl: "/models/cine57/SM_Barstool_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 95, materials: {"MI_Barstool_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_DiveBar_VOL2_Textures_Unique_TX_Barstool_01a_ALB.TX_Barstool_01a_ALB_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_DiveBar_VOL2_Textures_Unique_TX_Barstool_01a_NRM.TX_Barstool_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_DiveBar_VOL2_Textures_Unique_TX_Barstool_01a_RMA.TX_Barstool_01a_RMA.jpg"}} },
  { id: "box01", name: "纸盒", category: "容器与箱子", fileName: "SM_Box01.glb", fileUrl: "/models/cine57/SM_Box01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 21, materials: {"MI_Box01":{"baseColor":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_Box01_D.T_Box01_D_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_Box01_N.T_Box01_N_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_Box01_N.T_Box01_N.jpg"}} },
  { id: "garbagebasket01", name: "垃圾篮", category: "容器与箱子", fileName: "SM_GarbageBasket01.glb", fileUrl: "/models/cine57/SM_GarbageBasket01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 44, materials: {"MI_GarbageBasket01":{"baseColor":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_GarbageBasket01_D.T_GarbageBasket01_D_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_GarbageBasket01_N.T_GarbageBasket01_N_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_GarbageBasket01_N.T_GarbageBasket01_N.jpg"}} },
  { id: "microwave01", name: "微波炉", category: "厨房与餐具", fileName: "SM_Microwave01.glb", fileUrl: "/models/cine57/SM_Microwave01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 222, materials: {"MI_Microwave01":{"baseColor":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_Microwave01_D.T_Microwave01_D_baseColor.jpg","normal":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_Microwave01_N.T_Microwave01_N_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_KitchenPack_v03_Textures_T_Microwave01_N.T_Microwave01_N.jpg"}} },
  { id: "binder-01a", name: "文件夹", category: "书籍与办公", fileName: "SM_Binder_01a.glb", fileUrl: "/models/cine57/SM_Binder_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 77, materials: {"Mi_OfficeClutter_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_OfficeScatterItems_01a_DIF.TX_OfficeScatterItems_01a_DIF_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_Default_Grey.TX_Default_Grey_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_OfficeScatterItems_01a_NRM.TX_OfficeScatterItems_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_OfficeScatterItems_01a_NRM.TX_OfficeScatterItems_01a_NRM.jpg"}} },
  { id: "clock-01a", name: "时钟", category: "书籍与办公", fileName: "SM_Clock_01a.glb", fileUrl: "/models/cine57/SM_Clock_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 91, materials: {"Mi_Clock_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_Clock_01a_DIF.TX_Clock_01a_DIF_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_Default_Grey.TX_Default_Grey_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_Clock_01a_NRM.TX_Clock_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_Clock_01a_NRM.TX_Clock_01a_NRM.jpg"},"M_Glass":{"metallic":1,"roughness":0.5,"opacityValue":0.3}} },
  { id: "coffeecup-01a", name: "咖啡杯", category: "厨房与餐具", fileName: "SM_CoffeeCup_01a.glb", fileUrl: "/models/cine57/SM_CoffeeCup_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 130, materials: {"Mi_OfficeClutter_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_OfficeScatterItems_01a_DIF.TX_OfficeScatterItems_01a_DIF_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_Default_Grey.TX_Default_Grey_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_OfficeScatterItems_01a_NRM.TX_OfficeScatterItems_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Office_Textures_TX_OfficeScatterItems_01a_NRM.TX_OfficeScatterItems_01a_NRM.jpg"}} },
  { id: "bathroom-sink-01a", name: "卫浴水槽", category: "卫浴", fileName: "SM_Bathroom_Sink_01a.glb", fileUrl: "/models/cine57/SM_Bathroom_Sink_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 692, materials: {"MI_Bathroom_Sink_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL15_Bathroom_Textures_TX_Bathroom_Sink_01a_ALB.TX_Bathroom_Sink_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL15_Bathroom_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL15_Bathroom_Textures_TX_Bathroom_Sink_01a_NRM.TX_Bathroom_Sink_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL15_Bathroom_Textures_TX_Bathroom_Sink_01a_RMA.TX_Bathroom_Sink_01a_RMA.jpg"}} },
  { id: "cabinetset-01a", name: "收纳柜组", category: "家具", fileName: "SM_CabinetSet_01a.glb", fileUrl: "/models/cine57/SM_CabinetSet_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 143, materials: {"MI_Cabinet_Set_01d":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_CabinetSet_01d_ALB.TX_CabinetSet_01d_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_CabinetSet_01d_NRM.TX_CabinetSet_01d_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_CabinetSet_01d_RMA.TX_CabinetSet_01d_RMA.jpg"},"MI_Cabinet_Set_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_CabinetSet_01a_ALB.TX_CabinetSet_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_CabinetSet_01a_NRM.TX_CabinetSet_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburban_Household_VOL17_ModularCabinets_Textures_TX_CabinetSet_01a_RMA.TX_CabinetSet_01a_RMA.jpg"}} },
  { id: "desk-set-01a", name: "烟灰缸", category: "日用小物", fileName: "SM_Desk_Set_01a.glb", fileUrl: "/models/cine57/SM_Desk_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 111, materials: {"MI_Desk_Set_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Set_01a_ALB.TX_Desk_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Set_01a_NRM.TX_Desk_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Desk_Set_01a_RMA.TX_Desk_Set_01a_RMA.jpg"}} },
  { id: "file-cabinent-03a", name: "文件柜", category: "家具", fileName: "SM_File_Cabinent_03a.glb", fileUrl: "/models/cine57/SM_File_Cabinent_03a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 194, materials: {"MI_File_Cabinent_03a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_File_Cabinent_03a_ALB.TX_File_Cabinent_03a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_File_Cabinent_03a_NRM.TX_File_Cabinent_03a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_File_Cabinent_03a_RMA.TX_File_Cabinent_03a_RMA.jpg"}} },
  { id: "office-supplies-set-01a", name: "办公用品", category: "书籍与办公", fileName: "SM_Office_Supplies_Set_01a.glb", fileUrl: "/models/cine57/SM_Office_Supplies_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 51, materials: {"MI_Office_Supplies_Set_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Office_Supplies_Set_01a_ALB.TX_Office_Supplies_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Office_Supplies_Set_01a_NRM.TX_Office_Supplies_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Office_Supplies_Set_01a_RMA.TX_Office_Supplies_Set_01a_RMA.jpg"}} },
  { id: "printer-01a", name: "打印机", category: "书籍与办公", fileName: "SM_Printer_01a.glb", fileUrl: "/models/cine57/SM_Printer_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 485, materials: {"MI_Printer_01a":{"baseColor":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Printer_01a_ALB.TX_Printer_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Printer_01a_NRM.TX_Printer_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_EnvHouse_Suburbs_VOL19_Office_Textures_TX_Printer_01a_RMA.TX_Printer_01a_RMA.jpg"}} },
  { id: "flat-rock-02", name: "扁石 A", category: "石头", fileName: "SM_flat_rock_02.glb", fileUrl: "/models/cine57/SM_flat_rock_02.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 128, materials: {"MI_Flat_rock_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_BC_H.T_Flat_rock_01_tiled_BC_H_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_N.T_Flat_rock_01_tiled_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_N.T_Flat_rock_01_tiled_N.jpg"}} },
  { id: "flat-rock-03", name: "扁石 B", category: "石头", fileName: "SM_flat_rock_03.glb", fileUrl: "/models/cine57/SM_flat_rock_03.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 101, materials: {"MI_Flat_rock_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_BC_H.T_Flat_rock_01_tiled_BC_H_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_N.T_Flat_rock_01_tiled_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Flat_rock_01_tiled_N.T_Flat_rock_01_tiled_N.jpg"}} },
  { id: "mountain-rock-small-01-1", name: "山石 A", category: "石头", fileName: "SM_mountain_rock_small_01_1.glb", fileUrl: "/models/cine57/SM_mountain_rock_small_01_1.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 83, materials: {"MI_mountain_rocks_small_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_01_small_BC.T_rocks_01_small_BC_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_01_small_N.T_rocks_01_small_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_rocks_01_small_N.T_rocks_01_small_N.jpg"}} },
  { id: "stone-01", name: "石块", category: "石头", fileName: "SM_stone_01.glb", fileUrl: "/models/cine57/SM_stone_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 14, materials: {"MI_Big_rock_03":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Big_rock_03_BC_H.T_Big_rock_03_BC_H_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Big_rock_03_N.T_Big_rock_03_N_normal.jpg","rma":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Rocks_Textures_T_Big_rock_03_N.T_Big_rock_03_N.jpg"}} },
  { id: "air-mattress-01", name: "充气床垫", category: "户外", fileName: "SM_AirMattress_01.glb", fileUrl: "/models/cine57/SM_AirMattress_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 77, materials: {"MI_AirMattress_01a":{"baseColor":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_AirMattress_01_ALB.TX_AirMattress_01_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_AirMattress_01_NRM.TX_AirMattress_01_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_AirMattress_01_RMA.TX_AirMattress_01_RMA.jpg"}} },
  { id: "binoculars-01", name: "双筒望远镜", category: "户外", fileName: "SM_Binoculars_01.glb", fileUrl: "/models/cine57/SM_Binoculars_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 164, materials: {"MI_Binoculars_01a":{"baseColor":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_Binoculars_01_ALB.TX_Binoculars_01_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_Binoculars_01_NRM.TX_Binoculars_01_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_Binoculars_01_RMA.TX_Binoculars_01_RMA.jpg"}} },
  { id: "camping-grill-01", name: "露营烤架", category: "户外", fileName: "SM_CampingGrill_01.glb", fileUrl: "/models/cine57/SM_CampingGrill_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 147, materials: {"MI_CampingGrill_01a":{"baseColor":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_CampingGrill_ALB.TX_CampingGrill_ALB_baseColor.jpg","normal":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_CampingGrill_NRM.TX_CampingGrill_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Camping_Textures_Unique_TX_CampingGrill_RMA.TX_CampingGrill_RMA.jpg"}} },
  { id: "dryer-01a", name: "烘干机", category: "卫浴", fileName: "SM_Dryer_01a.glb", fileUrl: "/models/cine57/SM_Dryer_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 298, materials: {"MI_Dryer_01a":{"baseColor":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Dryer_01a_ALB.TX_Dryer_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Dryer_01a_NRM.TX_Dryer_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Dryer_01a_RMA.TX_Dryer_01a_RMA.jpg"}} },
  { id: "laundry-basket-01a", name: "洗衣篮", category: "容器与箱子", fileName: "SM_Laundry_Basket_01a.glb", fileUrl: "/models/cine57/SM_Laundry_Basket_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 263, materials: {"MI_Laundry_Basket_01a":{"baseColor":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Laundry_Basket_01a_ALB.TX_Laundry_Basket_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Laundry_Basket_01a_NRM.TX_Laundry_Basket_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Laundromat_VOL2_Laundry_Textures_TX_Laundry_Basket_01a_RMA.TX_Laundry_Basket_01a_RMA.jpg"}} },
  { id: "book-set-01b", name: "书堆 C", category: "书籍与办公", fileName: "SM_Book_Set_01b.glb", fileUrl: "/models/cine57/SM_Book_Set_01b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 32, materials: {"MI_Bookset_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_ALB.TX_Bookset_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_NRM.TX_Bookset_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_01a_RMA.TX_Bookset_01a_RMA.jpg"}} },
  { id: "book-set-nn-01a", name: "书堆 D", category: "书籍与办公", fileName: "SM_Book_Set_NN_01a.glb", fileUrl: "/models/cine57/SM_Book_Set_NN_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 336, materials: {"MI_Bookset_NN_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_NN_01a_ALB.TX_Bookset_NN_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_NN_01a_NRM.TX_Bookset_NN_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Bookset_NN_01a_RMA.TX_Bookset_NN_01a_RMA.jpg"}} },
  { id: "trophy-set-01a", name: "奖杯组", category: "玩具/装饰品", fileName: "SM_Trophy_Set_01a.glb", fileUrl: "/models/cine57/SM_Trophy_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 255, materials: {"MI_Trophy_Set_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Trophy_Set_01a_ALB.TX_Trophy_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Trophy_Set_01a_NRM.TX_Trophy_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL12_Decor_Textures_TX_Trophy_Set_01a_RMA.TX_Trophy_Set_01a_RMA.jpg"}} },
  { id: "vase-set-01a", name: "花瓶组 A", category: "玩具/装饰品", fileName: "SM_Vase_Set_01a.glb", fileUrl: "/models/cine57/SM_Vase_Set_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 55, materials: {"MI_Vase_Set_01a":{"baseColor":"/models/cine57/tex/_Props_Suburban_Household_VOL8_Decor_Textures_TX_Vase_Set_01a_ALB.TX_Vase_Set_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburban_Household_VOL8_Decor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburban_Household_VOL8_Decor_Textures_TX_Vase_Set_01a_NRM.TX_Vase_Set_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburban_Household_VOL8_Decor_Textures_TX_Vase_Set_01a_RMA.TX_Vase_Set_01a_RMA.jpg"}} },
  { id: "figurine-01a", name: "人偶摆件 A", category: "玩具/装饰品", fileName: "SM_Figurine_01a.glb", fileUrl: "/models/cine57/SM_Figurine_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 305, materials: {"MI_Figurine_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Figurine_01a_ALB.TX_Figurine_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Figurine_01a_NRM.TX_Figurine_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Figurine_01a_RMA.TX_Figurine_01a_RMA.jpg"}} },
  { id: "figurine-01b", name: "人偶摆件 B", category: "玩具/装饰品", fileName: "SM_Figurine_01b.glb", fileUrl: "/models/cine57/SM_Figurine_01b.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 288, materials: {"MI_Figurine_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Figurine_01a_ALB.TX_Figurine_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Figurine_01a_NRM.TX_Figurine_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Figurine_01a_RMA.TX_Figurine_01a_RMA.jpg"}} },
  { id: "knick-knack-84a", name: "小摆件 A", category: "玩具/装饰品", fileName: "SM_Knick_Knack_84a.glb", fileUrl: "/models/cine57/SM_Knick_Knack_84a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 408, materials: {"MI_Knick_Knacks_84a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knack_84a_ALB.TX_Knick_Knack_84a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knack_84a_NRM.TX_Knick_Knack_84a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Knick_Knack_84a_RMA.TX_Knick_Knack_84a_RMA.jpg"}} },
  { id: "knickknacks-05a", name: "小摆件 B", category: "玩具/装饰品", fileName: "SM_Knickknacks_05a.glb", fileUrl: "/models/cine57/SM_Knickknacks_05a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 50, materials: {"MI_Knickknacks_05a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL21_RetroDecor_Textures_TX_Knickknacks_05a_ALB.TX_Knickknacks_05a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL21_RetroDecor_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL21_RetroDecor_Textures_TX_Knickknacks_05a_NRM.TX_Knickknacks_05a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL21_RetroDecor_Textures_TX_Knickknacks_05a_RMA.TX_Knickknacks_05a_RMA.jpg"}} },
  { id: "shelves-01a", name: "置物架", category: "家具", fileName: "SM_Shelves_01a.glb", fileUrl: "/models/cine57/SM_Shelves_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 833, materials: {"MI_Shelves_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Shelves_01a_ALB.TX_Shelves_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Shelves_01a_NRM.TX_Shelves_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Shelves_01a_RMA.TX_Shelves_01a_RMA.jpg"},"MI_Shelves_01b":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Shelves_01a_ALB.TX_Shelves_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Shelves_01a_NRM.TX_Shelves_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Shelves_01a_RMA.TX_Shelves_01a_RMA.jpg"}} },
  { id: "wooden-statues-01a", name: "木雕摆件", category: "玩具/装饰品", fileName: "SM_Wooden_Statues_01a.glb", fileUrl: "/models/cine57/SM_Wooden_Statues_01a.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 699, materials: {"MI_Wooden_Statues_01a":{"baseColor":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Wooden_Statues_01a_ALB.TX_Wooden_Statues_01a_ALB_baseColor.jpg","opacity":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Fill_01_RMA.TX_Fill_01_RMA_opacity.jpg","normal":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Wooden_Statues_01a_NRM.TX_Wooden_Statues_01a_NRM_normal.jpg","rma":"/models/cine57/tex/_Props_Suburbs_VOL25_KnickKnacks_Textures_TX_Wooden_Statues_01a_RMA.TX_Wooden_Statues_01a_RMA.jpg"}} },
  { id: "orange-tree-01-01", name: "橙树 A", category: "树木", fileName: "sm_OrangeTree_01_01.glb", fileUrl: "/models/cine57/sm_OrangeTree_01_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 2538, materials: {"mi_OrangeTree_01_01":{"baseColor":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_01_01_bc.t_OrangeTree_01_01_bc_baseColor.jpg","opacity":"/models/cine57/tex/Venice_BaseMaterials_BaseTextures_01_t_Masks_01_01.t_Masks_01_01_opacity.jpg","normal":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_01_01_n.t_OrangeTree_01_01_n_normal.jpg"},"mi_OrangeTree_02_01":{"baseColor":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_02_01_bc.t_OrangeTree_02_01_bc_baseColor.jpg","opacity":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_02_01_m.t_OrangeTree_02_01_m_opacity.jpg","normal":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_02_01_n.t_OrangeTree_02_01_n_normal.jpg"},"mi_Orange_01_01":{"baseColor":"/models/cine57/tex/Venice_Environment_Orange_01_t_Orange_01_01_bc.t_Orange_01_01_bc_baseColor.jpg","opacity":"/models/cine57/tex/Venice_BaseMaterials_BaseTextures_01_t_Masks_01_01.t_Masks_01_01_opacity.jpg","normal":"/models/cine57/tex/Venice_Environment_Orange_01_t_Orange_01_01_n.t_Orange_01_01_n_normal.jpg"}} },
  { id: "orange-tree-01-02", name: "橙树 B", category: "树木", fileName: "sm_OrangeTree_01_02.glb", fileUrl: "/models/cine57/sm_OrangeTree_01_02.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 2473, materials: {"mi_OrangeTree_01_01":{"baseColor":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_01_01_bc.t_OrangeTree_01_01_bc_baseColor.jpg","opacity":"/models/cine57/tex/Venice_BaseMaterials_BaseTextures_01_t_Masks_01_01.t_Masks_01_01_opacity.jpg","normal":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_01_01_n.t_OrangeTree_01_01_n_normal.jpg"},"mi_OrangeTree_02_01":{"baseColor":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_02_01_bc.t_OrangeTree_02_01_bc_baseColor.jpg","opacity":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_02_01_m.t_OrangeTree_02_01_m_opacity.jpg","normal":"/models/cine57/tex/Venice_Environment_OrangeTree_01_t_OrangeTree_02_01_n.t_OrangeTree_02_01_n_normal.jpg"}} },
  { id: "shrub-a", name: "灌木 A", category: "灌木", fileName: "KB3D_LND_PropShrub_A_Main.glb", fileUrl: "/models/cine57/KB3D_LND_PropShrub_A_Main.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 5340, materials: {"KB3D_LND_AtlasFlowersA":{"baseColor":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasFlowersA_basecolor.KB3D_LND_AtlasFlowersA_basecolor_baseColor.jpg","opacity":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasFlowersA_opacity.KB3D_LND_AtlasFlowersA_opacity_opacity.jpg","normal":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasFlowersA_normal.KB3D_LND_AtlasFlowersA_normal_normal.jpg"},"KB3D_LND_AtlasLeafB":{"baseColor":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasLeafB_basecolor.KB3D_LND_AtlasLeafB_basecolor_baseColor.jpg","opacity":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasLeafB_opacity.KB3D_LND_AtlasLeafB_opacity_opacity.jpg","normal":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasLeafB_normal.KB3D_LND_AtlasLeafB_normal_normal.jpg"}} },
  { id: "shrub-b", name: "灌木 B", category: "灌木", fileName: "KB3D_LND_PropShrub_B_Main.glb", fileUrl: "/models/cine57/KB3D_LND_PropShrub_B_Main.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 4726, materials: {"KB3D_LND_AtlasFlowersA":{"baseColor":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasFlowersA_basecolor.KB3D_LND_AtlasFlowersA_basecolor_baseColor.jpg","opacity":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasFlowersA_opacity.KB3D_LND_AtlasFlowersA_opacity_opacity.jpg","normal":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasFlowersA_normal.KB3D_LND_AtlasFlowersA_normal_normal.jpg"},"KB3D_LND_AtlasLeafB":{"baseColor":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasLeafB_basecolor.KB3D_LND_AtlasLeafB_basecolor_baseColor.jpg","opacity":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasLeafB_opacity.KB3D_LND_AtlasLeafB_opacity_opacity.jpg","normal":"/models/cine57/tex/london_Textures_KB3D_LND_AtlasLeafB_normal.KB3D_LND_AtlasLeafB_normal_normal.jpg"}} },
  { id: "grass-01-1", name: "草丛 A", category: "草", fileName: "SM_grass_01_1.glb", fileUrl: "/models/cine57/SM_grass_01_1.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 7, materials: {"MI_grass_01":{"baseColor":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Foliage_Textures_T_grass_01_BC_M.T_grass_01_BC_M_baseColor.jpg","normal":"/models/cine57/tex/_Enviroments_Mountain_Environment_Set_Foliage_Textures_T_grass_01_N.T_grass_01_N_normal.jpg"}} },
  { id: "flower-01-01", name: "花丛 A", category: "花", fileName: "sm_Flower_01_01.glb", fileUrl: "/models/cine57/sm_Flower_01_01.glb", unitScale: 1, source: CINE57_SOURCE, sizeKb: 158, materials: {"mi_Flower_01_01":{"baseColor":"/models/cine57/tex/Paris_Environment_Restaurant_Flower_01_t_Flower_01_01_bc.t_Flower_01_01_bc_baseColor.jpg","opacity":"/models/cine57/tex/Paris_Environment_Restaurant_Flower_01_t_Flower_01_01_m.t_Flower_01_01_m_opacity.jpg","normal":"/models/cine57/tex/Paris_Environment_Restaurant_Flower_01_t_Flower_01_01_n.t_Flower_01_01_n_normal.jpg"}} },
  { id: "ual2-college-student", name: "男大学生角色（纹理测试）", category: "角色", fileName: "UAL2_UE_Anims.glb", fileUrl: "/anims/cine57/UAL2_UE_Anims.glb", unitScale: 1, source: "Cine57 / UAL2", sizeKb: 8242, previewAppearance: "character-texture-test" },
];

export const MODEL_LIBRARY: ModelLibraryEntry[] = attachModelUsageInstructions(MODEL_LIBRARY_BASE);

export function getModelLibraryEntry(id: string | undefined): ModelLibraryEntry | null {
  if (!id) return null;
  return MODEL_LIBRARY.find((entry) => entry.id === id) ?? null;
}
