// 从 world.prompts.ts 拆出的世界结构生成类 prompt：分层生成/本地化/导入抽取/结构回填/主题世界/结构章节/公理建议。
import type { WorldReferenceMode } from "@ai-novel/shared/types/worldWizard";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import {
  type WorldAxiomSuggestionPromptInput,
  type WorldConsistencyPromptInput,
  type WorldDeepeningQuestionsPromptInput,
  type WorldImportExtractionPromptInput,
  type WorldInspirationConceptCardLocalizationPromptInput,
  type WorldInspirationConceptCardPromptInput,
  type WorldLayerGenerationPromptInput,
  type WorldLayerLocalizationPromptInput,
  type NovelThemeWorldGenerationPromptInput,
  type WorldPropertyOptionsPromptInput,
  type WorldReferenceInspirationPromptInput,
  type WorldStructureBackfillPromptInput,
  type WorldStructureSectionPromptInput,
  type WorldVisualizationPromptInput,
} from "./world.promptTypes";
import {
  worldAxiomSuggestionSchema,
  worldConceptCardSchema,
  worldConsistencyIssuesSchema,
  worldDeepeningQuestionsSchema,
  worldImportExtractionSchema,
  worldLooseObjectSchema,
  novelThemeWorldGenerationSchema,
  worldPropertyOptionsPayloadSchema,
} from "./world.promptSchemas";
import { worldReferenceInspirationPayloadSchema } from "../../../services/world/worldReferenceSchema";
import { worldStructuredDataSchema, worldStructureSectionOutputSchema } from "../../../services/world/worldSchemas";
import { worldVisualizationDraftSchema } from "../../../services/world/worldVisualizationSchema";
import {
  buildStructureSectionInstructions,
} from "../../../services/world/worldServiceShared";

import { normalizeWorldStructureSectionPayload, sanitizeLooseWorldObject } from "./world.prompts";

export const worldLayerGenerationPrompt: PromptAsset<
  WorldLayerGenerationPromptInput,
  z.infer<typeof worldLooseObjectSchema>
> = {
  id: "world.layer.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldLooseObjectSchema,
  render: (input) => [
    new SystemMessage(
      [
        `你是世界观分层构建器，当前只负责生成 layer=${input.layerKey} 对应字段。`,
        "你的任务不是重写整套世界观，而是在既有世界基础上，为当前层补出可直接用于小说创作的结构化设定。",
        "",
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
        `输出字段只能来自：${input.targetFields.join(", ")}。`,
        "不得新增字段，不得输出目标字段之外的任何键。",
        "每个字段的值必须是可直接展示给作者阅读的简体中文文本字符串。",
        "禁止把字段值写成 JSON 对象、数组、嵌套结构、键值表或代码式结构。",
        "如果某层天然包含多个条目，请在同一个字符串内用自然语言分段或换行表达，不要输出嵌套对象。",
        "",
        "全局硬规则：",
        "1. 必须严格遵守：世界公理、模板约束、用户前置蓝图选择、既有已生成内容。",
        "2. 只能在现有基础上做补全与细化，不得推翻前面层已成立的设定。",
        "3. 若输入信息不足，必须做保守补全，优先给出低风险、可成立的设定，不要胡乱发散。",
        "4. 所有字段值必须使用简体中文。",
        "5. 输出必须是可直接落入世界设定库的结果，而不是分析说明或摘要。",
        "",
        "生成原则：",
        "1. 当前层必须与前面层形成因果关系、结构关联或运行关联，不能写成孤立描述。",
        "2. 每个字段都应回答“这个世界具体是怎么运作的”，而不是只写概念标签。",
        "3. 优先生成对后续剧情、人物、冲突、资源流动、秩序运转真正有作用的设定。",
        "4. 不要写空泛表达，如“社会复杂”“文化多元”“势力纷争”。必须具体说明复杂在哪里、多元在哪里、如何纷争。",
        "",
        "一致性要求：",
        "1. 不得与 existing 中已有内容冲突。",
        "2. 若某项设定必须承接 blueprint 或 summary 中的方向，必须明确体现承接关系。",
        "3. 若 classicElements 可参考，应吸收其有效结构，但不能机械复读模板说明。",
        "4. 若 pitfalls 已指出常见坑点，必须主动避开这些问题，不要把风险直接写进设定。",
        "",
        "质量要求：",
        "1. 每个字段都要具体、清楚、可用于写作，不要停留在百科式空描述。",
        "2. 设定应体现世界的运行逻辑、约束边界和叙事价值。",
        "3. 如果当前层天然依赖上层设定，必须显式体现这种依赖，而不是另起炉灶。",
        "",
        "边界规则：",
        "1. 不要输出总结段、前言、后记或解释说明。",
        "2. 不要补写 targetFields 之外的附加设定。",
        "3. 不要因为信息不足而留空字段；应尽量给出稳妥可用的内容。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        `name=${input.worldName}`,
        `worldType=${input.worldType}`,
        `template=${input.templateName}`,
        `templateDescription=${input.templateDescription}`,
        `classicElements=${input.classicElements.join(" | ") || "none"}`,
        `pitfalls=${input.pitfalls.join(" | ") || "none"}`,
        `axioms=${input.axioms || "none"}`,
        `summary=${input.summary || "none"}`,
        "blueprint=",
        input.blueprintPromptBlock,
        `existing=${input.existingJson}`,
        `ragContext=${input.ragContext || "none"}`,
        "",
        `请只生成当前 layer=${input.layerKey} 所需字段，并确保字段仅来自：${input.targetFields.join(", ")}。`,
      ].join("\n")
    ),
  ],
  postValidate: (output, input) =>
    sanitizeLooseWorldObject(
      output,
      input.targetFields,
      `world.layer.generate(${input.layerKey})`,
    ),
};

export const worldLayerLocalizationPrompt: PromptAsset<
  WorldLayerLocalizationPromptInput,
  z.infer<typeof worldLooseObjectSchema>
> = {
  id: "world.layer.localize",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldLooseObjectSchema,
  render: (input) => [
    new SystemMessage(
      [
        "你是世界观设定文本本地化助手。",
        "你的任务是将输入 JSON 对象中所有“展示给用户看的字段值”改写为自然、准确、可直接使用的简体中文。",
        "",
        "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "",
        "结构硬规则：",
        "1. 必须保持字段名完全不变。",
        "2. 不得新增字段、删除字段或调整层级结构。",
        `3. 输出字段只能来自当前层允许字段：${input.layerFields.join(", ")}。`,
        "",
        "内容规则：",
        "1. 必须保留原设定语义，不得改变世界规则、结构关系、因果逻辑或设定边界。",
        "2. 必须保留专有名词含义；若原专有名词已有合理中文形式，应优先使用自然中文表达。",
        "3. 不得补写新设定，不得删减已有有效信息。",
        "4. 不得把模糊表述擅自具体化为新的世界事实。",
        "",
        "本地化要求：",
        "1. 所有字段值都必须改写为简体中文。",
        "2. 不是机械翻译，而是要转写成符合中文小说世界设定语境的自然表达。",
        "3. 若原文存在英文思维、生硬直译、重复或不通顺表达，应在不改变原意前提下优化。",
        "4. 数组中的每一项也必须本地化，但要保持原有数量与对应关系不变。",
        "",
        "质量要求：",
        "1. 输出结果必须像可直接进入世界设定库的中文成稿，而不是翻译稿。",
        "2. 各字段值之间必须保持一致，不得出现术语前后不统一。",
        "3. 不要输出空泛润色，优先保证准确、稳定、可复用。",
        "",
        "边界规则：",
        "1. 如果输入中某些值本来已经是自然中文，可保留或仅做轻微润色，不要为了改而改。",
        "2. 如果某些 ID、代码式字段值属于结构标识而非展示文本，不要误翻。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        `layer=${input.layerKey}`,
        `fields=${input.layerFields.join(",")}`,
        `input=${input.sourcePayloadJson}`,
      ].join("\n")
    ),
  ],
  postValidate: (output, input) =>
    sanitizeLooseWorldObject(
      output,
      input.layerFields,
      `world.layer.localize(${input.layerKey})`,
    ),
};

export const worldImportExtractionPrompt: PromptAsset<
  WorldImportExtractionPromptInput,
  z.infer<typeof worldImportExtractionSchema>
> = {
  id: "world.import.extract",
  version: "v1",
  taskType: "fact_extraction",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldImportExtractionSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观导入抽取器。",
      "你的任务是从输入文本中提取可直接导入系统的世界设定 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "输出字段必须且只能包括：",
      "name, description, worldType, background, geography, magicSystem, politics, cultures, races, religions, technology, history, economy, conflicts, factions, templateKey, axioms。",
      "",
      "全局硬规则：",
      "1. 所有可展示文本必须使用简体中文。",
      "2. 只能提取输入文本中明确存在或可低风险归纳的信息，不得凭空补写完整设定。",
      "3. 如果某个字段在原文中没有足够依据，必须保守处理，优先返回空字符串、空数组或最小可成立内容，不要硬编。",
      "4. 输出目标是“世界设定导入”，不是总结文章，也不是赏析报告。",
      "5. 各字段之间必须一致，不得互相冲突。",
      "",
      "字段提取原则：",
      "1. name：提取世界名称；若原文未明确给出，使用最稳妥、最贴近文本的概括性名称，不要乱造花哨名字。",
      "2. description：概括世界整体面貌与核心特征，简洁但具体，不要写空话。",
      "3. worldType：提取世界基础类型，如都市异变、架空王朝、末世废土、近未来高压社会等，必须稳、准、可用于后续分类。",
      "4. background：提取世界形成背景、时代处境、根本局势或大环境前提。",
      "5. geography：提取关键地理格局、空间结构、区域分布或地点系统。",
      "6. magicSystem：提取超凡体系、力量规则、能力来源、代价与边界；若无相关内容，保守留空。",
      "7. politics：提取政体、权力结构、治理方式、统治关系或政治对抗。",
      "8. cultures：提取风俗、价值观、社会习惯、礼制、禁忌或文化分层。",
      "9. races：提取种族、族群、阶层型生物群体或特殊人群划分；没有则留空。",
      "10. religions：提取宗教、信仰体系、神话信奉、祭祀秩序或精神权威来源；没有则留空。",
      "11. technology：提取技术水平、生产力形态、工具系统、工业/信息/机械特征。",
      "12. history：提取关键历史阶段、断层、重大事件、旧秩序遗产或历史创伤。",
      "13. economy：提取资源流动、财富来源、产业结构、交换机制、生存成本或经济压迫结构。",
      "14. conflicts：提取世界层的核心矛盾、长期冲突来源、结构性对抗，不要写成单一剧情事件。",
      "15. factions：提取稳定存在的势力、组织、国家、阵营、集团或权力主体。",
      "16. templateKey：根据文本内容保守归类到最贴近的模板键；若文本无足够依据，使用最稳妥的默认归类，不要自造模板名。",
      "17. axioms：提取世界公理、硬性规则、不可违背的底层约束或默认运行逻辑。",
      "",
      "抽取质量要求：",
      "1. 优先提取对后续小说创作最有用的硬结构信息，而不是零碎细节。",
      "2. 不要把人物个人经历、具体剧情桥段、单次事件误写成世界层字段。",
      "3. 不要把相邻字段写成同义重复，例如 background、history、description 不应只是换说法重复同一段。",
      "4. 若输入文本明显偏故事简介，也要尽量只抽世界层信息，过滤人物线与情节线噪音。",
      "",
      "缺失处理规则：",
      "1. 不确定时优先保守，不要脑补。",
      "2. 没有明确宗教/种族/魔法/科技内容时，不要为了结构完整而强行生成。",
      "3. 若 factions 可抽取为数组或列表内容，应尽量保留为可用的结构性描述，而不是模糊概括。",
      "",
      "输出必须严格符合 worldImportExtractionSchema。",
    ].join("\n")),
    new HumanMessage(input.content),
  ],
};

export const worldStructureBackfillPrompt: PromptAsset<
  WorldStructureBackfillPromptInput,
  z.infer<typeof worldStructuredDataSchema>
> = {
  id: "world.structure.backfill",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldStructuredDataSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界结构化提取器。",
      "你的任务是根据输入文本，提取可直接进入系统使用的世界结构数据。",
      "这不是赏析，不是总结，也不是自由补全，而是把文本中的世界层信息整理为稳定的 JSON 结构。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "JSON 结构必须严格为：",
      "{",
      '  "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '  "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '  "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],',
      '  "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
      '  "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}],',
      '  "relations": {',
      '    "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],',
      '    "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]',
      "  }",
      "}",
      "",
      "全局硬规则：",
      "1. 只能提取文本里明确存在或可低风险推断的信息，不得凭空编造完整世界结构。",
      "2. 所有值必须使用简体中文。",
      "3. 不要增加额外字段，不要改字段名，不要删字段层级。",
      "4. 若某类信息确实缺失，应保守返回空数组或最小可成立内容，不要硬编。",
      "5. 各部分之间必须自洽，不得互相冲突。",
      "",
      "字段判定规则：",
      "1. profile：用于概括这个世界的整体身份、气质、主题和核心矛盾，必须站在“世界层”而不是“角色层”总结。",
      "2. rules：用于提取这个世界默认成立的规则、代价、边界、禁忌和共同后果。",
      "3. factions：是抽象阵营、立场、路线、阶层板块或意识形态阵营。",
      "4. forces：是具体组织、圈层、公司、部门、帮会、机构、网络或可落地行动主体。",
      "5. locations：是具有世界辨识度和叙事功能的地点，不是随便提到的普通场景。",
      "6. relations：用于提取 forces 之间的关系，以及 force 对 location 的控制关系。",
      "",
      "关键区分要求：",
      "1. 像“社会压力机制”“行业运作规则”“默认人际法则”“生存代价”“资源约束”这类世界默认机制，必须写进 rules，不要塞进 factions 或 forces。",
      "2. faction 写的是‘哪一类人/立场/路线’，force 写的是‘具体谁在执行、控制、施压’。",
      "3. 若一个对象只有抽象立场，没有明确组织实体，优先归入 factions；若它能作为具体行动单位出现，优先归入 forces。",
      "",
      "profile 要求：",
      "1. summary：概括世界最核心的面貌与运行现实，不要写剧情简介。",
      "2. identity：写清这个世界的基本身份，例如工业废土都市、权力高压王朝、行业丛林社会等。",
      "3. tone：写世界整体气质，如冷硬、压抑、粗粝、腐朽、诡谲，不要空话。",
      "4. themes：提取世界层主题，不要写单个角色命题。",
      "5. coreConflict：写世界最核心、最长期成立的结构性矛盾。",
      "",
      "rules 要求：",
      "1. axioms 只收录真正具有世界约束力的规则。",
      "2. 每条 axiom 都要写清：规则是什么、代价是什么、边界在哪里、如何被维持。",
      "3. taboo 是世界明确不能碰的禁忌、红线或高压触发点。",
      "4. sharedConsequences 是这个世界里多数人共同承担的默认后果或系统性代价。",
      "",
      "factions / forces 要求：",
      "1. factions 必须体现立场、信条、目标和方法差异，不要做成空泛标签。",
      "2. representativeForceIds 必须尽量对应真正代表该 faction 的具体 force。",
      "3. forces 必须写清其权力来源、当前目标、施压方式和叙事作用。",
      "4. 没有明确 leader 时可保守处理，但不要乱造人名。",
      "",
      "locations 要求：",
      "1. 只保留真正重要的地点。",
      "2. summary 要说明地点特征，narrativeFunction 要说明它在故事中的用途。",
      "3. risk、entryConstraint、exitCost 要体现这个地点为何有门槛、有压力或有代价。",
      "",
      "relations 要求：",
      "1. forceRelations 只记录真正有意义的关系，不要把所有对象机械连边。",
      "2. relation 要写清关系类型，tension 要写清当前紧张点，detail 要说明关系为何成立。",
      "3. locationControls 只在文本能支持 force 与 location 存在控制、占据、管理、封锁、渗透等关系时再写。",
      "",
      "质量要求：",
      "1. 优先提取对后续创作最有用的硬结构信息，而不是零碎细节。",
      "2. 不要把人物个人动机、具体剧情桥段、感情推进写进世界结构。",
      "3. 不要让 profile、rules、factions、forces 彼此换说法重复。",
      "4. 输出结果必须像一份可直接落库的世界结构草案，而不是读书笔记。",
    ].join("\n")),
    new HumanMessage(input.promptSource),
  ],
};

export const novelThemeWorldGenerationPrompt: PromptAsset<
  NovelThemeWorldGenerationPromptInput,
  z.infer<typeof novelThemeWorldGenerationSchema>
> = {
  id: "novel.world.generate_from_theme",
  version: "v2",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  repairPolicy: {
    maxAttempts: 0,
  },
  semanticRetryPolicy: {
    maxAttempts: 0,
  },
  outputSchema: novelThemeWorldGenerationSchema,
  render: (input) => [
    new SystemMessage([
      "你是网文小说的本书世界设计师。",
      "你的任务是根据一本小说的主题、卖点、读者承诺和类型信息，生成“这本书专属使用”的世界结构数据。",
      "这不是外部世界库百科，也不是剧情大纲；输出必须服务于后续角色、大纲、章节和一致性生成。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "title": "...",',
      '  "coverSummary": "...",',
      '  "worldType": "...",',
      '  "structuredData": {',
      '    "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '    "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '    "factions": [{"id":"faction-1","name":"...","position":"...","goals":["..."],"representativeForceIds":["force-1"]}],',
      '    "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","currentObjective":"...","pressure":"..."}],',
      '    "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","controllingForceIds":["force-1"]}],',
      '    "relations": {',
      '      "forceRelations": [{"sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"..."}],',
      '      "locationControls": [{"forceId":"force-1","locationId":"location-1","relation":"..."}]',
      "    }",
      "  }",
      "}",
      "",
      "输出容量硬约束：",
      "1. 这里只生成可开书的世界种子，不是完整百科；后续在世界手册中按需要扩写。",
      "2. 名称、id、类型等短字段不超过 16 个汉字；说明字段不超过 24 个汉字；数组每项不超过 12 个汉字且最多 2 项。",
      "3. 不重复解释同一规则、势力或地点；除 JSON 键名和 id 外，全部文本控制在约 1,800 个汉字以内。",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      "2. 世界必须紧扣本书主题，不得生成一套与小说卖点无关的通用百科。",
      "3. 世界设定必须能约束后续生成：力量有代价，秩序有执行者，冲突有来源，地点有叙事功能。",
      "4. 不要写主角个人剧情，不要替小说生成完整大纲，不要把单次事件当成世界规则。",
      "5. 允许根据小说信息做合理补全；如果信息不足，要生成稳妥、低风险、可继续扩展的本书舞台。",
      input.openingOnly
        ? "6. 当前只准备开篇切片：仅生成前 3-5 章会直接读取的规则、势力和地点，不扩写远期百科。"
        : "6. 当前生成可持续扩展的本书世界基础。",
      "",
      "内容数量要求：",
      "1. rules.axioms 生成 2-3 条硬规则。",
      "2. factions 生成 1-2 个与本书直接相关的阵营或立场板块。",
      "3. forces 生成 2-3 个会行动或施压的具体势力、组织或机构。",
      "4. locations 生成 2-3 个会反复使用的舞台地点。",
      "5. relations 中只连接真正有意义的势力关系和地点控制关系，不要机械全连接。",
      "",
      "字段质量要求：",
      "1. title 要像一个可展示的世界名，不要只是小说名。",
      "2. coverSummary 用 1-2 句说明读者一眼能看到的世界面貌。",
      "3. profile.summary 要说明“这个世界长什么样、如何运行、为什么适合这本书”。",
      "4. rules 每条 axiom 必须写清规则、代价、边界和执行方式。",
      "5. faction 是立场或阶层板块，force 是具体执行者；不要混淆。",
      "6. location 必须有风险或叙事功能。",
      "7. forbidden/taboo/sharedConsequences 要帮助后续生成避免违背世界规则。",
      "",
      "面向生成链的要求：",
      "1. 角色生成应该能从 forces/factions 中找到身份、归属、冲突来源。",
      "2. 大纲生成应该能从 locations/coreConflict 中找到舞台和长期矛盾。",
      "3. 章节生成应该能从 rules/taboo/sharedConsequences 中获得不可违背的约束。",
      "4. 这份世界是本书副本，可以之后保存到世界库；不要假设它已经是通用模板。",
    ].join("\n")),
    new HumanMessage([
      `小说标题：${input.novelTitle}`,
      `小说简介：${input.description || "未填写"}`,
      `目标读者：${input.targetAudience || "未填写"}`,
      `核心卖点：${input.bookSellingPoint || "未填写"}`,
      `前30章承诺：${input.first30ChapterPromise || "未填写"}`,
      `商业标签：${input.commercialTags.length > 0 ? input.commercialTags.join("、") : "未填写"}`,
      `主类型：${input.genreName || "未选择"}`,
      `主故事模式：${input.primaryStoryModeName || "未选择"}`,
      `副故事模式：${input.secondaryStoryModeName || "未选择"}`,
      `准备范围：${input.openingOnly ? "开篇 3-5 章世界切片" : "本书世界基础"}`,
      input.storyMacroContext?.trim() ? `故事宏观规划：\n${input.storyMacroContext.trim()}` : "",
      input.bookContractContext?.trim() ? `书级创作约定：\n${input.bookContractContext.trim()}` : "",
    ].join("\n")),
  ],
};

export const worldStructureSectionPrompt: PromptAsset<
  WorldStructureSectionPromptInput,
  z.infer<typeof worldStructureSectionOutputSchema>
> = {
  id: "world.structure.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldStructureSectionOutputSchema,
  render: (input) => [
    new SystemMessage(
      [
        `你是世界结构化补全器，当前只负责补全 section=${input.section} 对应的 JSON。`,
        "你的任务不是重写整套世界结构，而是在现有结构基础上，为指定 section 补出可直接落库的结构化内容。",
        "",
        "只输出一个合法 JSON，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "",
        buildStructureSectionInstructions(input.section),
        "",
        "全局硬规则：",
        "1. 只能补全当前 section 对应的数据，不得输出其他 section 的内容。",
        "2. 不要破坏已有 ID；如果沿用现有实体，必须复用当前结构中的 id。",
        "3. 不得编造与输入文本、当前结构或绑定建议明显冲突的信息。",
        "4. 如果信息不足，必须做保守补全，优先补“低风险、可成立、能落地”的结构，不要硬造复杂设定。",
        "5. 所有文本值必须使用简体中文。",
        "",
        "一致性要求：",
        "1. 输出内容必须与当前结构保持连续，不得推翻已成立的世界规则、阵营关系、地点功能或既有绑定。",
        "2. 若当前 section 涉及实体复用，优先延续现有命名、归属与关系网络。",
        "3. 若当前绑定建议给出了优先连接方向，应尽量沿用，除非与输入文本明显冲突。",
        "",
        "section 补全规则：",
        "1. 如果 section=factions，必须同时考虑 factions 和 forces 的区分与联动。",
        "2. 禁止把社会压力机制、行业规则、人际法则、默认秩序、普遍代价这类世界默认机制写进 factions / forces；这些内容属于 rules。",
        "3. faction 写抽象阵营、立场、路线；force 写具体组织、部门、圈层、公司、帮会、机构、网络等行动主体。",
        "4. 如果 section=locations，必须填写 narrativeFunction、risk、entryConstraint、exitCost，且内容必须具体可用，不能空泛。",
        "5. 如果 section=relations，只允许输出 forceRelations 和 locationControls，不得新增其他关系块。",
        "6. relations 必须只连接真正有依据的实体，不要机械连边。",
        "",
        "质量要求：",
        "1. 输出必须像可直接进入世界结构库的成稿，而不是分析说明。",
        "2. 每个字段都要具体、稳定、可供后续创作使用，避免“势力复杂”“地点危险”“关系紧张”这类空话。",
        "3. 优先补足真正影响世界运行和叙事推进的硬结构，不要被零碎细节带偏。",
        "4. 若当前 section 天然依赖其他 section，必须体现这种结构关联，而不是孤立书写。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        input.promptSource,
        "",
        "当前结构：",
        JSON.stringify(input.currentStructure, null, 2),
        "",
        "当前绑定建议：",
        JSON.stringify(input.currentBindingSupport, null, 2),
      ].join("\n"),
    ),
  ],
  postValidate: (output, input) => normalizeWorldStructureSectionPayload(output, input),
};

export const worldAxiomSuggestionPrompt: PromptAsset<
  WorldAxiomSuggestionPromptInput,
  z.infer<typeof worldAxiomSuggestionSchema>
> = {
  id: "world.axioms.suggest",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldAxiomSuggestionSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界公理设计器。",
      "你的任务是为当前世界生成 5 条“核心公理”，作为后续世界构建、设定补全和剧情展开的最高约束层。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "数组元素必须全部是字符串，且全部使用简体中文。",
      "必须精确输出 5 条，不能多也不能少。",
      "",
      "全局硬规则：",
      "1. 每条公理都必须是“能约束后续生成”的硬规则，而不是口号、主题句或世界简介。",
      "2. 公理必须能直接影响后续世界搭建，例如限制代价、规定秩序、定义冲突来源、划定边界条件、明确默认后果。",
      "3. 只能基于输入中的世界类型、模板说明、世界摘要和蓝图约束来生成，不得脱离这些信息另起一套世界。",
      "4. 如果信息不足，优先生成低风险、通用但有约束力的公理，不要空泛发散。",
      "",
      "公理设计要求：",
      "1. 至少应覆盖以下关键约束中的大部分：代价、秩序、冲突来源、边界条件、默认后果、资源约束、权力限制、公开与隐秘规则。",
      "2. 每条公理都应回答“这个世界默认怎么运作，违反后会怎样，哪些事不能无代价发生”。",
      "3. 公理必须具体，例如可以约束力量使用、身份流动、资源获取、组织秩序、信息传播、社会压迫、越界代价等。",
      "4. 不要写成‘世界很残酷’‘人心复杂’‘强者为尊’这类空泛判断，除非它被具体化为可执行约束。",
      "5. 5 条公理之间尽量分工明确，不要换说法重复同一个意思。",
      "",
      "表达要求：",
      "1. 每条公理尽量写成一句完整、清楚、可直接引用的约束句。",
      "2. 不要写得太长，但必须足够具体，能拿去约束后续世界生成。",
      "3. 语言要像世界设定中的底层规则，而不是宣传文案或文学抒情。",
      "",
      "质量要求：",
      "1. 看完这 5 条，应该能大致理解这个世界的运行底线。",
      "2. 这些公理要能帮助后续自动生成避免跑偏、避免设定失真、避免无代价乱开。",
      "3. 不要生成互相冲突的公理。",
    ].join("\n")),
    new HumanMessage([
      `世界名=${input.worldName}`,
      `世界类型=${input.worldType}`,
      `模板=${input.templateName}`,
      `模板说明=${input.templateDescription}`,
      `世界摘要=${input.description}`,
      "蓝图约束：",
      input.blueprintPromptBlock,
    ].join("\n")),
  ],
};
